database:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: 'root'
  ports:
    - '8889:3306'

dba:
  image: phpmyadmin/phpmyadmin
  ports:
    - '8080:80'
  links:
    - database:db

php:
  build: .
  ports:
    - '10000:10000'
  links:
    - database:db
  volumes:
    - ./:/app
