<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, target-densitydpi=device-dpi, user-scalable=no">
    <title>Pesquisa de Inovação IEL</title>

    <link rel="stylesheet" type="text/css" href="/css/normalize.css" />
    <link rel="stylesheet" type="text/css" href="/css/foundation.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/demo.css" />
    <link rel="stylesheet" type="text/css" href="/css/contador.css" />
    <link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css" />
    <script src="/js/modernizr.custom.js"></script>
  </head>

  <body>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-88744224-1', 'auto');
      ga('send', 'pageview');
    </script>

    <div class="social-share-buttons">
      <a class="facebook button" target="_new" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($shareUrl); ?>" data-share-channel="facebook" data-state="<?php echo $state; ?>" data-company-size="<?php echo $companySize; ?>"></a>
      <a class="linkedin button" target="_new" href="https://www.linkedin.com/cws/share?url=<?php echo urlencode($shareUrl); ?>" data-share-channel="linkedin" data-state="<?php echo $state; ?>" data-company-size="<?php echo $companySize; ?>"></a>
    </div>

    <div class="container" style="height:100%;">
      <header>
        <div class="row text-center">
          <div class="columns">
            <img src="/img/iel/relatorio/logo.png" id="logo-medium" class="show-for-medium" style="max-height: 110px"/>
            <img src="/img/iel/logo-inovacao.png" id="logo-small-only" class="show-for-small-only " />
          </div>
          <div class="small-10 small-offset-2 medium-12 medium-offset-0 columns text-left text-center-mobile">
            <h2 class="semi-bold">Conheça seu nível de capacidade em gestão da inovação!</h2>
          </div>
        </div>

        <div class="row">
          <div class="small-10 small-offset-2 medium-12 medium-offset-0 columns congratulations">
            <h4>
              <span class="semi-bold">Parabéns!</span> Você concluiu sua auto-avaliação de Capacidade
              de Gestão da Inovação. Seu relatório completo está esperando por você no seu e-mail.
            </h4>
          </div>
        </div>
      </header>

      <main class="row" data-equalizer>
        <div class="small-10 small-offset-2 medium-6 medium-offset-0 columns">
          <div class="share-modal" data-equalizer-watch>
            <p class="semi-bold">
              Pensou em alguém que gostaria de responder esse formulário?
            </p>

            <form action="/share" method="post" id="share-form" data-state="<?php echo $state; ?>" data-company-size="<?php echo $companySize; ?>">
              <input class="fs-fields" name="name" type="text" required placeholder="Nome" />
              <input class="fs-fields" name="email" type="email" required placeholder="Email" />
              <input name="referer" type="hidden" value="<?php echo htmlspecialchars($referer) ?>" />

              <input class="submit-primary" type="submit" value="Enviar Convite"/>
            </form>
          </div>
        </div>

        <div class="small-10 small-offset-2 medium-6 medium-offset-0 columns text-center" data-equalizer-watch>
          <div class="graph-container">
            <div class="graph" data-progress="30">
            </div>
            <div class="graph-label" id="countdown-container">
              <span class="graph-label-text" id="countdown-text">30</span>
            </div>
          </div>

          <div class="graph-legend">
            <p>Esse formulário será reiniciado em instantes.</p>
            <a href="/contador" class="submit-secondary" id="restart-button">
              Reiniciar Agora
            </a>
          </div>
        </div>
      </main>

      <footer class="row text-center">
        <div class="small-12 columns conngratulations">
          <img src="/img/iel/logo-iel.png"/>
        </div>
      </footer>
    </div>



    <!-- start Mixpanel -->
    <script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
  0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
  for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
    mixpanel.init("029119b7e1fa503b52a32d240d8d5b52");</script>
    <!-- end Mixpanel -->

    <!-- Scripts -->
    <script type="text/javascript" src="/js/vendor/jquery.js"></script>
    <script type="text/javascript" src="/js/vendor/what-input.js"></script>
    <script type="text/javascript" src="/js/vendor/foundation.min.js"></script>
    <script src="/js/progressbar.js"></script>
    <script src="/js/contador.js"></script>
  </body>
</html>
