<html>
  <head>
    <title>Inovação IEL</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.4.4/sweetalert2.min.css">
    <link rel="stylesheet" href="https://unpkg.com/jquery-modal@0.8.0/jquery.modal.min.css">
  </head>
  <body>
    <ul>
      <li><a href="/admin/responses">Extrair Respostas</a></li>
      <li><a href="#">Editar contatos</a></li>
      <li><a href="/admin/logout">Logout</a></li>
    </ul>
    <h1>Inovação IEL: Editar contatos</h1>
    <hr/>

    <div id="content">
      <table>
        <thead>
          <tr>
            <td><strong>UF</strong></td>
            <td><strong>Nome</strong></td>
            <td><strong>Email</strong></td>
            <td><strong>Telefone(s)</strong></td>
            <td><strong>Ações</strong></td>
          </tr>
        </thead>
        <tbody>
          <?php if (empty($contacts)): ?>
            <tr>
              <td colspan="5">Não há contatos cadastrados</td>
            </tr>
          <?php else: ?>
            <?php foreach ($contacts as $contact): ?>
              <tr>
                <td><?= $contact->uf ?></td>
                <td><?= $contact->name ?></td>
                <td><?= $contact->email ?></td>
                <td><?= $contact->phone ?></td>
                <td>
                  <a href="#" class="edit-contact" data-id="<?= $contact->id ?>">Editar</a>
                  <a href="#" class="delete-contact" data-id="<?= $contact->id ?>">Excluir</a>
                </td>
              </tr>
            <?php endforeach; ?>
          <?php endif; ?>
        </tbody>
      </table>

      <div class="text-right">
        <a href="#" class="new-contact">Novo Contato</a>
      </div>

      <form id="contact-form" class="modal" style="display: none">
        <label for="uf">UF</label>
        <select name="uf" id="uf">
          <option value="ac">AC</option>
          <option value="al">AL</option>
          <option value="am">AM</option>
          <option value="ap">AP</option>
          <option value="ba">BA</option>
          <option value="ce">CE</option>
          <option value="df">DF</option>
          <option value="es">ES</option>
          <option value="go">GO</option>
          <option value="ma">MA</option>
          <option value="mg">MG</option>
          <option value="ms">MS</option>
          <option value="mt">MT</option>
          <option value="pa">PA</option>
          <option value="pb">PB</option>
          <option value="pe">PE</option>
          <option value="pi">PI</option>
          <option value="pr">PR</option>
          <option value="sc">SC</option>
          <option value="se">SE</option>
          <option value="sp">SP</option>
          <option value="rj">RJ</option>
          <option value="rn">RN</option>
          <option value="ro">RO</option>
          <option value="rr">RR</option>
          <option value="rs">RS</option>
          <option value="to">TO</option>
        </select>
        <br />
        <label for="name">Nome</label>
        <input type="text" name="name" id="name">
        <br />
        <label for="email">Email</label>
        <input type="text" name="email" id="email">
        <br />
        <label for="phone">Telefone(s)</label>
        <input type="text" name="phone" id="phone">
        <br />
        <input type="hidden" name="contact_id" id="contact_id" value="">

        <input type="submit" value="Salvar"/>
      </form>
    </div>

    <script src="https://cdn.jsdelivr.net/sweetalert2/6.4.4/sweetalert2.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://unpkg.com/jquery-modal@0.8.0/jquery.modal.min.js"></script>
    <script type="text/javascript">
      $(function() {
        var contacts = [];
        <?php foreach($contacts as $contact): ?>
          contacts.push({
            id: <?= json_encode($contact->id) ?>,
            name: <?= json_encode($contact->name) ?>,
            uf: <?= json_encode($contact->uf) ?>,
            email: <?= json_encode($contact->email) ?>,
            phone: <?= json_encode($contact->phone) ?>,
          });
        <?php endforeach; ?>

        $('.delete-contact').click(function() {
          var $this = $(this);

          swal({
            title: 'Você tem certeza?',
            text: "Você não poderá reverter a reverter deste contato.",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sim, delete!',
            cancelButtonText: 'Cancelar'
          }).then(function () {
            var contact_id = $this.data('id');
            $.ajax({
              type: 'POST',
              url: '#',
              data: { action: 'delete', id: contact_id },
              success: function(response) {
                window.location.reload();
              },
              error: function() {
                swal({ title: 'Oops!', text: 'Não foi possível realizar essa ação. Tente novamente em alguns minutos.', type: 'error'})
              }
            })
          })
        });

        $('.new-contact').click(function() {
          $('#uf').val("");
          $('#name').val("");
          $('#email').val("");
          $('#phone').val("");
          $('#contact_id').val("");

          $('#contact-form').modal();
        });

        $('.edit-contact').click(function() {
          var $this = $(this);
          var data_id = $this.data('id');
          var contact = contacts.find(function(contact) { return contact.id == data_id });

          $('#contact_id').val(data_id);
          $('#uf').val(contact.uf);
          $('#name').val(contact.name);
          $('#email').val(contact.email);
          $('#phone').val(contact.phone);

          $('#contact-form').modal();
        })

        $('#contact-form').submit(function(e) {
          e.preventDefault();

          var id = $('#contact_id').val();
          var uf = $('#uf').val();
          var name = $('#name').val();
          var email = $('#email').val();
          var phone = $('#phone').val();

          $.ajax({
            type: 'POST',
            url: '#',
            data: { action: 'upsert', id: id, uf: uf, name: name, email: email, phone: phone },
            success: function(response) {
              window.location.reload();
            },
            error: function() {
              swal({ title: 'Oops!', text: 'Não foi possível realizar essa ação. Tente novamente em alguns minutos.', type: 'error'})
            }
          })
        });
      });
    </script>
  </body>
</html>
