<!DOCTYPE html>
<html lang="pt" class="no-js">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, target-densitydpi=device-dpi, user-scalable=no">

  <meta property="og:title" content="Sua empresa é realmente inovadora?" />
	<meta property="og:description" content="IEL disponibiliza ferramenta para avaliar a capacidade de inovação de sua empresa. Acesse e descubra o seu nível!" />
  <meta property="og:url" content="http://inovacaoiel.herokuapp.com/" />
  <meta property="og:image" content="http://inovacaoiel.herokuapp.com/img/iel/opengraph6.jpg" />
	<meta property="og:type" content="website" />

  <title>Gestão da Inovação - IEL</title>

  <link rel="stylesheet" type="text/css" href="css/normalize.css" />
  <link rel="stylesheet" type="text/css" href="css/demo.css" />
  <link rel="stylesheet" type="text/css" href="css/component.css" />
  <link rel="stylesheet" type="text/css" href="css/cs-select.css" />
  <script src="js/modernizr.custom.js"></script>

</head>
<body>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-88744224-1', 'auto');
    ga('send', 'pageview');
  </script>

  <div class="container">

    <div class="fs-form-wrap" id="fs-form-wrap">
      <img src="img/iel/logo-inovacao.png" style="margin-top:20px; margin-left:20px; margin-bottom: 13px">
      <form id="main-form" class="fs-form fs-form-full ac-fill" action="<?php echo ($showShareCounter ? '/contador' : '/relatorio'); ?>" method="POST" autocomplete="off">
        <ol class="fs-fields">
          <li data-input-trigger data-hide-last-button data-hide-next-button>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label">Auto avaliação da capacidade em Gestão da Inovação</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower">
              <a href="#" class="fs-button">Começar</a>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q1">Qual categoria melhor define o seu negócio?</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group fs-radio-custom clearfix" style="margin-top:25px !important">
                <span><input required name="q1" type="radio" id="q1-0" value="0"><label for="q1-0">Água, gás e saneamento </label></span>
                <span><input name="q1" type="radio" id="q1-1" value="1"><label for="q1-1">Indústrias em geral </label></span>
                <span><input name="q1" type="radio" id="q1-2" value="2"><label for="q1-2">Setor de saúde</label></span>
                <span><input name="q1" type="radio" id="q1-3" value="3"><label for="q1-3">Alimentos processados </label></span>
                <span><input name="q1" type="radio" id="q1-4" value="4"><label for="q1-4">Materiais diversos </label></span>
                <span><input name="q1" type="radio" id="q1-5" value="5"><label for="q1-5">Setor de seguros</label></span>
                <span><input name="q1" type="radio" id="q1-6" value="6"><label for="q1-6">Bancos</label></span>
                <span><input name="q1" type="radio" id="q1-7" value="7"><label for="q1-7">Mineração</label></span>
                <span><input name="q1" type="radio" id="q1-8" value="8"><label for="q1-8">Setor de transporte</label></span>
                <span><input name="q1" type="radio" id="q1-9" value="9"><label for="q1-9">Carnes e derivados </label></span>
                <span><input name="q1" type="radio" id="q1-10" value="10"><label for="q1-10">Negócios de lazer e eventos</label></span>
                <span><input name="q1" type="radio" id="q1-11" value="11"><label for="q1-11">Siderurgia e metalurgia</label></span>
                <span><input name="q1" type="radio" id="q1-12" value="12"><label for="q1-12">Construção civil e intermediação </label></span>
                <span><input name="q1" type="radio" id="q1-13" value="13"><label for="q1-13">Papel e madeira </label></span>
                <span><input name="q1" type="radio" id="q1-14" value="14"><label for="q1-14">Tecnologia da informação</label></span>
                <span><input name="q1" type="radio" id="q1-15" value="15"><label for="q1-15">Construção pesada e engenharia </label></span>
                <span><input name="q1" type="radio" id="q1-16" value="16"><label for="q1-16">Petróleo, gás e combustíveis </label></span>
                <span><input name="q1" type="radio" id="q1-17" value="17"><label for="q1-17">Telecomunicações</label></span>
                <span><input name="q1" type="radio" id="q1-18" value="18"><label for="q1-18">Energia elétrica </label></span>
                <span><input name="q1" type="radio" id="q1-19" value="19"><label for="q1-19">Química e petroquímica </label></span>
                <span><input name="q1" type="radio" id="q1-20" value="20"><label for="q1-20">Têxteis</label></span>
                <span><input name="q1" type="radio" id="q1-21" value="21"><label for="q1-21">Equipamentos, máquinas e peças</label></span>
                <span><input name="q1" type="radio" id="q1-22" value="22"><label for="q1-22">Roupas, calçados e acessórios </label></span>
                <span><input name="q1" type="radio" id="q1-23" value="23"><label for="q1-23">Utilidades domésticas</label></span>
                <span><input name="q1" type="radio" id="q1-24" value="24"><label for="q1-24">Holdings</label></span>
                <span><input name="q1" type="radio" id="q1-25" value="25"><label for="q1-25">Serviços diversos</label></span>
                <span><input name="q1" type="radio" id="q1-26" value="26"><label for="q1-26">Varejo</label></span>
                <span><input name="q1" type="radio" id="q1-27" value="27"><label for="q1-27">Hotelaria e Restaurantes </label></span>
                <span><input name="q1" type="radio" id="q1-28" value="28"><label for="q1-28">Imóveis comerciais e shoppings </label></span>
                <span><input name="q1" type="radio" id="q1-29" value="29"><label for="q1-29">Serviços financeiros</label></span>
                <span><input name="q1" type="radio" id="q1-30" value="30"><label for="q1-30">Indústrias de alimentos </label></span>
                <span><input name="q1" type="radio" id="q1-31" value="31"><label for="q1-31">Educação</label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q2">Localidade de atuação</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group fs-radio-custom fs-checkbox-group fs-map clearfix">
                <input type="hidden" name="q2" id="state-selection"/>

                <div class="show-mobile">
                  <div class="cf">
                    <span class="uf-area"><input type="checkbox" id="tp-0" value="0"><label for="tp-0">Todo o território nacional</label></span>
                    <span class="uf-area"><input type="checkbox" id="tp-1" value="1"><label for="tp-1">Norte</label></span>
                    <span class="uf-area"><input type="checkbox" id="tp-2" value="2"><label for="tp-2">Nordeste</label></span>
                    <span class="uf-area"><input type="checkbox" id="tp-3" value="3"><label for="tp-3">Centro-Oeste</label></span>
                    <span class="uf-area"><input type="checkbox" id="tp-4" value="4"><label for="tp-4">Sudeste</label></span>
                    <span class="uf-area"><input type="checkbox" id="tp-5" value="5"><label for="tp-5">Sul</label></span>
                  </div>
                  <span class="uf"><input type="checkbox" id="q2-1" value="ac"><label for="q2-1">AC</label></span>
                  <span class="uf"><input type="checkbox" id="q2-2" value="al"><label for="q2-2">AL</label></span>
                  <span class="uf"><input type="checkbox" id="q2-3" value="am"><label for="q2-3">AM</label></span>
                  <span class="uf"><input type="checkbox" id="q2-4" value="ap"><label for="q2-4">AP</label></span>
                  <span class="uf"><input type="checkbox" id="q2-5" value="ba"><label for="q2-5">BA</label></span>
                  <span class="uf"><input type="checkbox" id="q2-6" value="ce"><label for="q2-6">CE</label></span>
                  <span class="uf"><input type="checkbox" id="q2-7" value="df"><label for="q2-7">DF</label></span>
                  <span class="uf"><input type="checkbox" id="q2-8" value="es"><label for="q2-8">ES</label></span>
                  <span class="uf"><input type="checkbox" id="q2-9" value="go"><label for="q2-9">GO</label></span>
                  <span class="uf"><input type="checkbox" id="q2-10" value="ma"><label for="q2-10">MA</label></span>
                  <span class="uf"><input type="checkbox" id="q2-11" value="mg"><label for="q2-11">MG</label></span>
                  <span class="uf"><input type="checkbox" id="q2-12" value="ms"><label for="q2-12">MS</label></span>
                  <span class="uf"><input type="checkbox" id="q2-13" value="mt"><label for="q2-13">MT</label></span>
                  <span class="uf"><input type="checkbox" id="q2-14" value="pa"><label for="q2-14">PA</label></span>
                  <span class="uf"><input type="checkbox" id="q2-15" value="pb"><label for="q2-15">PB</label></span>
                  <span class="uf"><input type="checkbox" id="q2-16" value="pe"><label for="q2-16">PE</label></span>
                  <span class="uf"><input type="checkbox" id="q2-17" value="pi"><label for="q2-17">PI</label></span>
                  <span class="uf"><input type="checkbox" id="q2-18" value="pr"><label for="q2-18">PR</label></span>
                  <span class="uf"><input type="checkbox" id="q2-19" value="sc"><label for="q2-19">SC</label></span>
                  <span class="uf"><input type="checkbox" id="q2-20" value="se"><label for="q2-20">SE</label></span>
                  <span class="uf"><input type="checkbox" id="q2-21" value="sp"><label for="q2-21">SP</label></span>
                  <span class="uf"><input type="checkbox" id="q2-22" value="rj"><label for="q2-22">RJ</label></span>
                  <span class="uf"><input type="checkbox" id="q2-23" value="rn"><label for="q2-23">RN</label></span>
                  <span class="uf"><input type="checkbox" id="q2-24" value="ro"><label for="q2-24">RO</label></span>
                  <span class="uf"><input type="checkbox" id="q2-25" value="rr"><label for="q2-25">RR</label></span>
                  <span class="uf"><input type="checkbox" id="q2-26" value="rs"><label for="q2-26">RS</label></span>
                  <span class="uf"><input type="checkbox" id="q2-27" value="to"><label for="q2-27">TO</label></span>
                </div>

                <div class="hide-mobile">
                  <div class="half-width">
                    <embed src="img/brazilmap.svg"/>
                  </div>
                  <div class="half-width">
                    <div class="fs-radio-group fs-radio-custom clearfix fs-large-options fs-align-left map-areas">
                      <span class="uf-area"><input type="checkbox" id="tp-6" value="0"><label for="tp-6">Todo o território nacional</label></span>
                      <span class="uf-area"><input type="checkbox" id="tp-7" value="1"><label for="tp-7">Norte</label></span>
                      <span class="uf-area"><input type="checkbox" id="tp-8" value="2"><label for="tp-8">Nordeste</label></span>
                      <span class="uf-area"><input type="checkbox" id="tp-9" value="3"><label for="tp-9">Centro-Oeste</label></span>
                      <span class="uf-area"><input type="checkbox" id="tp-10" value="4"><label for="tp-10">Sudeste</label></span>
                      <span class="uf-area"><input type="checkbox" id="tp-11" value="5"><label for="tp-11">Sul</label></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question data-company-size-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q3">Qual é o porte de sua empresa?</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group fs-radio-custom clearfix fs-large-options fs-align-left">
                <span>
                  <input name="q3" type="radio" id="q3-1" value="1">
                  <label for="q3-1">Faturamento anual até R$ 60 mil</label>
                </span>
                <span>
                  <input name="q3" type="radio" id="q3-2" value="2">
                  <label for="q3-2">Faturamento anual até R$ 360 mil</label>
                </span>
                <span>
                  <input name="q3" type="radio" id="q3-3" value="3">
                  <label for="q3-3">Faturamento anual entre R$ 360 mil e R$ 3,6 milhões</label>
                </span>
                <span>
                  <input name="q3" type="radio" id="q3-4" value="4">
                  <label for="q3-4">Faturamento anual entre R$ 3,6 milhões e R$ 16 milhões</label>
                </span>
                <span>
                  <input name="q3" type="radio" id="q3-5" value="5">
                  <label for="q3-5">Faturamento anual entre R$ 16 milhões e R$ 90 milhões</label>
                </span>
                <span>
                  <input name="q3" type="radio" id="q3-6" value="6">
                  <label for="q3-6">Faturamento anual entre R$ 90 milhões e R$ 300 milhões</label>
                </span>
                <span>
                  <input name="q3" type="radio" id="q3-7" value="7">
                  <label for="q3-7">Faturamento maior do que R$ 300 milhões</label>
                </span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-hide-next-button data-register-event="respondeu-parte-1">
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label">Agora, nos fale um pouco mais sobre sua empresa.</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower">
              <a href="#" class="fs-button">Continuar</a>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q4"> Dentre as opções abaixo, qual a maior prioridade para sua empresa atualmente? </label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group fs-radio-custom clearfix fs-large-options fs-align-left">
                <span><input required name="q4" type="radio" id="q4-0" value="0"><label for="q4-0">Aumento da gama de bens e serviços </label></span>
                <span><input name="q4" type="radio" id="q4-1" value="1"><label for="q4-1">Tempo reduzido de resposta às necessidades dos consumidores</label></span>
                <span><input name="q4" type="radio" id="q4-2" value="2"><label for="q4-2">Melhoria da comunicação e da interação entre as diferentes atividades de negócios</label></span>
                <span><input name="q4" type="radio" id="q4-3" value="3"><label for="q4-3">Aumento da visibilidade ou da exposição dos produtos</label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q5"> Dentre as opções abaixo, qual a maior prioridade para sua empresa atualmente? </label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group fs-radio-custom clearfix fs-large-options fs-align-left">
                <span><input required name="q5" type="radio" id="q5-0" value="0"><label for="q5-0">Desenvolvimento de produtos não agressivos ao meio ambiente </label></span>
                <span><input name="q5" type="radio" id="q5-1" value="1"><label for="q5-1">Entrada em novos mercados</label></span>
                <span><input name="q5" type="radio" id="q5-2" value="2"><label for="q5-2">Melhoria das condições de trabalho</label></span>
                <span><input name="q5" type="radio" id="q5-3" value="3"><label for="q5-3">Redução dos custos de concepção dos produtos</label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q6"> Dentre as opções abaixo, qual a maior prioridade para sua empresa atualmente? </label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group fs-radio-custom clearfix fs-large-options fs-align-left">
                <span><input required name="q6" type="radio" id="q6-0" value="0"><label for="q6-0">Aumento ou manutenção da parcela de mercado (market-share) </label></span>
                <span><input name="q6" type="radio" id="q6-1" value="1"><label for="q6-1">Melhoria da gestão de informações</label></span>
                <span><input name="q6" type="radio" id="q6-2" value="2"><label for="q6-2">Aumento da visibilidade ou da exposição dos produtos</label></span>
                <span><input name="q6" type="radio" id="q6-3" value="3"><label for="q6-3">Aumento da flexibilidade de produção ou provisão de serviços</label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q7">A liderança inspira os funcionários a serem criativos, encorajando a mudança e implantando uma cultura de melhoria e aprendizado no sentido da excelência?</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q7" type="radio" id="q7-0" value="0" class="sexy-radio"><label for="q7-0"><span>1</span><br/><span class="subtitle">…eventual e informalmente.</span></label></span>
                <span><input name="q7" type="radio" id="q7-1" value="1" class="sexy-radio"><label for="q7-1"><span>2</span></label></span>
                <span><input name="q7" type="radio" id="q7-2" value="2" class="sexy-radio"><label for="q7-2"><span>3</span></label></span>
                <span><input name="q7" type="radio" id="q7-3" value="3" class="sexy-radio"><label for="q7-3"><span>4</span><br/><span class="subtitle">…frequentemente, a partir de orientações formais estabelecidas.</span></label></span>
                <span><input name="q7" type="radio" id="q7-4" value="4" class="sexy-radio"><label for="q7-4"><span>5</span></label></span>
                <span><input name="q7" type="radio" id="q7-5" value="5" class="sexy-radio"><label for="q7-5"><span>6</span></label></span>
                <span><input name="q7" type="radio" id="q7-6" value="6" class="sexy-radio"><label for="q7-6"><span>7</span><br/><span class="subtitle">…em interações sistemáticas suportadas por processos e práticas de gestão institucionalizados.</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q8">As pessoas são estimuladas a sugerirem novas ideias para produtos (bens ou serviços) ou processos?</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q8" type="radio" id="q8-0" value="0" class="sexy-radio"><label for="q8-0"><span>1</span><br/><span class="subtitle">…eventual e informalmente.</span></label></span>
                <span><input name="q8" type="radio" id="q8-1" value="1" class="sexy-radio"><label for="q8-1"><span>2</span></label></span>
                <span><input name="q8" type="radio" id="q8-2" value="2" class="sexy-radio"><label for="q8-2"><span>3</span></label></span>
                <span><input name="q8" type="radio" id="q8-3" value="3" class="sexy-radio"><label for="q8-3"><span>4</span><br/><span class="subtitle">…frequentemente, a partir de orientações formais estabelecidas.</span></label></span>
                <span><input name="q8" type="radio" id="q8-4" value="4" class="sexy-radio"><label for="q8-4"><span>5</span></label></span>
                <span><input name="q8" type="radio" id="q8-5" value="5" class="sexy-radio"><label for="q8-5"><span>6</span></label></span>
                <span><input name="q8" type="radio" id="q8-6" value="6" class="sexy-radio"><label for="q8-6"><span>7</span><br/><span class="subtitle">…sistematicamente, por meio de mecanismos de incentivo, avaliação e reconhecimento.</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q9">A empresa fornece a seus funcionários acesso ao conhecimento necessário à realização de algo novo?       </label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q9" type="radio" id="q9-0" value="0" class="sexy-radio"><label for="q9-0"><span>1</span><br/><span class="subtitle">…informalmente.</span></label></span>
                <span><input name="q9" type="radio" id="q9-1" value="1" class="sexy-radio"><label for="q9-1"><span>2</span></label></span>
                <span><input name="q9" type="radio" id="q9-2" value="2" class="sexy-radio"><label for="q9-2"><span>3</span></label></span>
                <span><input name="q9" type="radio" id="q9-3" value="3" class="sexy-radio"><label for="q9-3"><span>4</span><br/><span class="subtitle">…formalmente, por meio de capacitações previamente planejadas.</span></label></span>
                <span><input name="q9" type="radio" id="q9-4" value="4" class="sexy-radio"><label for="q9-4"><span>5</span></label></span>
                <span><input name="q9" type="radio" id="q9-5" value="5" class="sexy-radio"><label for="q9-5"><span>6</span></label></span>
                <span><input name="q9" type="radio" id="q9-6" value="6" class="sexy-radio"><label for="q9-6"><span>7</span><br/><span class="subtitle">…sistematicamente, por meio de um processo institucional de gestão do conhecimento.</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q10">Nos últimos dois anos, a empresa implementou decisões estratégicas...</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q10" type="radio" id="q10-0" value="0" class="sexy-radio"><label for="q10-0"><span>1</span><br/><span class="subtitle">…reativas, para se adequar aos seus concorrentes.</span></label></span>
                <span><input name="q10" type="radio" id="q10-1" value="1" class="sexy-radio"><label for="q10-1"><span>2</span></label></span>
                <span><input name="q10" type="radio" id="q10-2" value="2" class="sexy-radio"><label for="q10-2"><span>3</span></label></span>
                <span><input name="q10" type="radio" id="q10-3" value="3" class="sexy-radio"><label for="q10-3"><span>4</span><br/><span class="subtitle">…para diferenciar-se dos concorrentes de mercado.</span></label></span>
                <span><input name="q10" type="radio" id="q10-4" value="4" class="sexy-radio"><label for="q10-4"><span>5</span></label></span>
                <span><input name="q10" type="radio" id="q10-5" value="5" class="sexy-radio"><label for="q10-5"><span>6</span></label></span>
                <span><input name="q10" type="radio" id="q10-6" value="6" class="sexy-radio"><label for="q10-6"><span>7</span><br/><span class="subtitle">…pioneiras, exigindo respostas de seus concorrentes.</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q11">A empresa possui uma estrutura que suporta a comunicação, o compartilhamento e a disseminação de informações?</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q11" type="radio" id="q11-0" value="0" class="sexy-radio"><label for="q11-0"><span>1</span><br/><span class="subtitle">...entre funcionários de uma mesma área.</span></label></span>
                <span><input name="q11" type="radio" id="q11-1" value="1" class="sexy-radio"><label for="q11-1"><span>2</span></label></span>
                <span><input name="q11" type="radio" id="q11-2" value="2" class="sexy-radio"><label for="q11-2"><span>3</span></label></span>
                <span><input name="q11" type="radio" id="q11-3" value="3" class="sexy-radio"><label for="q11-3"><span>4</span><br/><span class="subtitle">...entre áreas afins.</span></label></span>
                <span><input name="q11" type="radio" id="q11-4" value="4" class="sexy-radio"><label for="q11-4"><span>5</span></label></span>
                <span><input name="q11" type="radio" id="q11-5" value="5" class="sexy-radio"><label for="q11-5"><span>6</span></label></span>
                <span><input name="q11" type="radio" id="q11-6" value="6" class="sexy-radio"><label for="q11-6"><span>7</span><br/><span class="subtitle">...integrada e ágil entre todas as áreas e níveis da organização.</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q12">Nos últimos dois anos, a política de investimento financeiro da empresa esteve focada?</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix fs-large-options sexy-radio-group">
                <span><input required name="q12" type="radio" id="q12-0" value="0" class="sexy-radio"><label for="q12-0"><span>1</span><br/><span class="subtitle">...essencialmente em seus produtos (bens ou serviços) tradicionais.</span></label></span>
                <span><input name="q12" type="radio" id="q12-1" value="1" class="sexy-radio"><label for="q12-1"><span>2</span></label></span>
                <span><input name="q12" type="radio" id="q12-2" value="2" class="sexy-radio"><label for="q12-2"><span>3</span></label></span>
                <span><input name="q12" type="radio" id="q12-3" value="3" class="sexy-radio"><label for="q12-3"><span>4</span><br/><span class="subtitle">...em significativa parcela de produtos (bens ou serviços) inovadores.</span></label></span>
                <span><input name="q12" type="radio" id="q12-4" value="4" class="sexy-radio"><label for="q12-4"><span>5</span></label></span>
                <span><input name="q12" type="radio" id="q12-5" value="5" class="sexy-radio"><label for="q12-5"><span>6</span></label></span>
                <span><input name="q12" type="radio" id="q12-6" value="6" class="sexy-radio"><label for="q12-6"><span>7</span><br/><span class="subtitle">...em um planejado balanceamento entre produtos (bens ou serviços) tradicionais e inovadores alinhados aos objetivos estratégicos.</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q13">A empresa é capaz de estruturar equipes de trabalho que dispõem do tempo, das ferramentas e dos conhecimentos necessários para o desenvolvimento de projetos de inovação?       </label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q13" type="radio" id="q13-0" value="0" class="sexy-radio"><label for="q13-0"><span>1</span><br/><span class="subtitle">...eventualmente, sem método definido.</span></label></span>
                <span><input name="q13" type="radio" id="q13-1" value="1" class="sexy-radio"><label for="q13-1"><span>2</span></label></span>
                <span><input name="q13" type="radio" id="q13-2" value="2" class="sexy-radio"><label for="q13-2"><span>3</span></label></span>
                <span><input name="q13" type="radio" id="q13-3" value="3" class="sexy-radio"><label for="q13-3"><span>4</span><br/><span class="subtitle">...frequentemente, com base nas atividades a serem desempenhadas.</span></label></span>
                <span><input name="q13" type="radio" id="q13-4" value="4" class="sexy-radio"><label for="q13-4"><span>5</span></label></span>
                <span><input name="q13" type="radio" id="q13-5" value="5" class="sexy-radio"><label for="q13-5"><span>6</span></label></span>
                <span><input name="q13" type="radio" id="q13-6" value="6" class="sexy-radio"><label for="q13-6"><span>7</span><br/><span class="subtitle">...sistematicamente, com base no planejamento estratégico, com monitoramento contínuo.</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q14">A empresa é capaz de identificar e analisar novas exigências e preferências de clientes atuais e potenciais?        </label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q14" type="radio" id="q14-0" value="0" class="sexy-radio"><label for="q14-0"><span>1</span><br/><span class="subtitle">...eventualmente e sem um método estruturado.</span></label></span>
                <span><input name="q14" type="radio" id="q14-1" value="1" class="sexy-radio"><label for="q14-1"><span>2</span></label></span>
                <span><input name="q14" type="radio" id="q14-2" value="2" class="sexy-radio"><label for="q14-2"><span>3</span></label></span>
                <span><input name="q14" type="radio" id="q14-3" value="3" class="sexy-radio"><label for="q14-3"><span>4</span><br/><span class="subtitle">...frequentemente, usando ferramentas e procedimentos.</span></label></span>
                <span><input name="q14" type="radio" id="q14-4" value="4" class="sexy-radio"><label for="q14-4"><span>5</span></label></span>
                <span><input name="q14" type="radio" id="q14-5" value="5" class="sexy-radio"><label for="q14-5"><span>6</span></label></span>
                <span><input name="q14" type="radio" id="q14-6" value="6" class="sexy-radio"><label for="q14-6"><span>7</span><br/><span class="subtitle">...sistematicamente, usando processos e práticas de gestão para transformá-las em oferta de valor.</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q15">Os processos implantados pela empresa estão caracterizados…</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q15" type="radio" id="q15-0" value="0" class="sexy-radio"><label for="q15-0"><span>1</span><br/><span class="subtitle">...pela baixa flexibilidade, com lentidão nas revisões das atividades.</span></label></span>
                <span><input name="q15" type="radio" id="q15-1" value="1" class="sexy-radio"><label for="q15-1"><span>2</span></label></span>
                <span><input name="q15" type="radio" id="q15-2" value="2" class="sexy-radio"><label for="q15-2"><span>3</span></label></span>
                <span><input name="q15" type="radio" id="q15-3" value="3" class="sexy-radio"><label for="q15-3"><span>4</span><br/><span class="subtitle">...pela definição das atividades para atender aos requisitos atuais.</span></label></span>
                <span><input name="q15" type="radio" id="q15-4" value="4" class="sexy-radio"><label for="q15-4"><span>5</span></label></span>
                <span><input name="q15" type="radio" id="q15-5" value="5" class="sexy-radio"><label for="q15-5"><span>6</span></label></span>
                <span><input name="q15" type="radio" id="q15-6" value="6" class="sexy-radio"><label for="q15-6"><span>7</span><br/><span class="subtitle">...pelo alto nível de flexibilidade, viabilizando rápidas adaptações em decorrência das necessidades futuras.</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q16">A empresa estabelece relações com outras empresas, associações industriais, consultores, universidades, centros de pesquisa etc. para desenvolver seus conhecimentos e competências?        </label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q16" type="radio" id="q16-0" value="0" class="sexy-radio"><label for="q16-0"><span>1</span><br/><span class="subtitle">...eventual e informalmente.</span></label></span>
                <span><input name="q16" type="radio" id="q16-1" value="1" class="sexy-radio"><label for="q16-1"><span>2</span></label></span>
                <span><input name="q16" type="radio" id="q16-2" value="2" class="sexy-radio"><label for="q16-2"><span>3</span></label></span>
                <span><input name="q16" type="radio" id="q16-3" value="3" class="sexy-radio"><label for="q16-3"><span>4</span><br/><span class="subtitle">...frequentemente e por meio de canais formais de relacionamento.</span></label></span>
                <span><input name="q16" type="radio" id="q16-4" value="4" class="sexy-radio"><label for="q16-4"><span>5</span></label></span>
                <span><input name="q16" type="radio" id="q16-5" value="5" class="sexy-radio"><label for="q16-5"><span>6</span></label></span>
                <span><input name="q16" type="radio" id="q16-6" value="6" class="sexy-radio"><label for="q16-6"><span>7</span><br/><span class="subtitle">...sistematicamente, integrando formalmente redes e grupos de cooperação para a inovação.</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q17">Nos últimos dois anos, o percentual de novos produtos (bens ou serviços) em relação ao portfólio pela empresa…</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q17" type="radio" id="q17-0" value="0" class="sexy-radio"><label for="q17-0"><span>1</span><br><span class="subtitle">foi pouco expressivo</span></label></span>
                <span><input name="q17" type="radio" id="q17-1" value="1" class="sexy-radio"><label for="q17-1"><span>2</span></label></span>
                <span><input name="q17" type="radio" id="q17-2" value="2" class="sexy-radio"><label for="q17-2"><span>3</span></label></span>
                <span><input name="q17" type="radio" id="q17-3" value="3" class="sexy-radio"><label for="q17-3"><span>4</span><br><span class="subtitle">teve significativo impacto na melhoria da rentabilidade</span></label></span>
                <span><input name="q17" type="radio" id="q17-4" value="4" class="sexy-radio"><label for="q17-4"><span>5</span></label></span>
                <span><input name="q17" type="radio" id="q17-5" value="5" class="sexy-radio"><label for="q17-5"><span>6</span></label></span>
                <span><input name="q17" type="radio" id="q17-6" value="6" class="sexy-radio"><label for="q17-6"><span>7</span><br><span class="subtitle">foi muito expressivo, colaborando para uma posição de liderança no mercado</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q18">Nos últimos dois anos, o tempo médio entre a identificação de uma oportunidade no mercado e a entrega de um novo produto (bem ou serviço) reduziu...</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q18" type="radio" id="q18-0" value="0" class="sexy-radio"><label for="q18-0"><span>1</span><br><span class="subtitle">de forma pouco significativa</span></label></span>
                <span><input name="q18" type="radio" id="q18-1" value="1" class="sexy-radio"><label for="q18-1"><span>2</span></label></span>
                <span><input name="q18" type="radio" id="q18-2" value="2" class="sexy-radio"><label for="q18-2"><span>3</span></label></span>
                <span><input name="q18" type="radio" id="q18-3" value="3" class="sexy-radio"><label for="q18-3"><span>4</span><br><span class="subtitle">significativamente, alcançando metas estabelecidas</span></label></span>
                <span><input name="q18" type="radio" id="q18-4" value="4" class="sexy-radio"><label for="q18-4"><span>5</span></label></span>
                <span><input name="q18" type="radio" id="q18-5" value="5" class="sexy-radio"><label for="q18-5"><span>6</span></label></span>
                <span><input name="q18" type="radio" id="q18-6" value="6" class="sexy-radio"><label for="q18-6"><span>7</span><br><span class="subtitle">expressivamente, tornando a empresa referência em tempo de resposta</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q19">Nos últimos dois anos, as menções positivas sobre a marca ou produtos (bens ou serviços) da empresa nas mídias sociais foram...</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q19" type="radio" id="q19-0" value="0" class="sexy-radio"><label for="q19-0"><span>1</span><br><span class="subtitle">pouco expressivas</span></label></span>
                <span><input name="q19" type="radio" id="q19-1" value="1" class="sexy-radio"><label for="q19-1"><span>2</span></label></span>
                <span><input name="q19" type="radio" id="q19-2" value="2" class="sexy-radio"><label for="q19-2"><span>3</span></label></span>
                <span><input name="q19" type="radio" id="q19-3" value="3" class="sexy-radio"><label for="q19-3"><span>4</span><br><span class="subtitle">expressivas, porém menos que os principais concorrentes</span></label></span>
                <span><input name="q19" type="radio" id="q19-4" value="4" class="sexy-radio"><label for="q19-4"><span>5</span></label></span>
                <span><input name="q19" type="radio" id="q19-5" value="5" class="sexy-radio"><label for="q19-5"><span>6</span></label></span>
                <span><input name="q19" type="radio" id="q19-6" value="6" class="sexy-radio"><label for="q19-6"><span>7</span><br><span class="subtitle">muito expressivas, sendo mais citada que todos os seus concorrentes</span></label></span>
              </div>
            </div>
          </li>
          <li data-input-trigger data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q20">Nos últimos dois anos, a empresa melhorou de forma significativa as condições de trabalho, obtendo um nível de satisfação dos funcionários...</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower" style="margin-bottom:80px;">
              <div class="fs-radio-group clearfix sexy-radio-group">
                <span><input required name="q20" type="radio" id="q20-0" value="0" class="sexy-radio"><label for="q20-0"><span>1</span><br><span class="subtitle">inferior a 50%</span></label></span>
                <span><input name="q20" type="radio" id="q20-1" value="1" class="sexy-radio"><label for="q20-1"><span>2</span></label></span>
                <span><input name="q20" type="radio" id="q20-2" value="2" class="sexy-radio"><label for="q20-2"><span>3</span></label></span>
                <span><input name="q20" type="radio" id="q20-3" value="3" class="sexy-radio"><label for="q20-3"><span>4</span><br><span class="subtitle">em torno de 75%</span></label></span>
                <span><input name="q20" type="radio" id="q20-4" value="4" class="sexy-radio"><label for="q20-4"><span>5</span></label></span>
                <span><input name="q20" type="radio" id="q20-5" value="5" class="sexy-radio"><label for="q20-5"><span>6</span></label></span>
                <span><input name="q20" type="radio" id="q20-6" value="6" class="sexy-radio"><label for="q20-6"><span>7</span><br><span class="subtitle">superior a 90%</span></label></span>
              </div>
            </div>
          </li>

          <li data-register-event="respondeu-parte-2" data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q21">Qual o nome da sua empresa?</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower">
              <input class="fs-anim-lower" name="q21" id="q21" type="text" placeholder="Digite aqui..." required />
            </div>
          </li>
          <li data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q22">Qual o seu nome?</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower">
              <input class="fs-anim-lower" name="q22" id="q22" type="text" placeholder="Digite o nome completo..." required />
            </div>
          </li>
          <li data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q23">Em qual e-mail deseja receber o relatório?</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower">
              <input class="fs-anim-lower" name="q23" id="q23" type="email" placeholder="seuemail@empresa.com.br" required />
            </div>
          </li>
          <li data-question data-state-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q24">Em que estado você fica?</label>
              </div>
            </div>

            <div class="content-container fs-anim-lower">
              <div>
                <select required name="q24" class="cs-select cs-skin-rotate cs-skin-underline">
                  <option value="ac">AC</option>
                  <option value="al">AL</option>
                  <option value="am">AM</option>
                  <option value="ap">AP</option>
                  <option value="ba">BA</option>
                  <option value="ce">CE</option>
                  <option value="df">DF</option>
                  <option value="es">ES</option>
                  <option value="go">GO</option>
                  <option value="ma">MA</option>
                  <option value="mg">MG</option>
                  <option value="ms">MS</option>
                  <option value="mt">MT</option>
                  <option value="pa">PA</option>
                  <option value="pb">PB</option>
                  <option value="pe">PE</option>
                  <option value="pi">PI</option>
                  <option value="pr">PR</option>
                  <option value="sc">SC</option>
                  <option value="se">SE</option>
                  <option value="sp">SP</option>
                  <option value="rj">RJ</option>
                  <option value="rn">RN</option>
                  <option value="ro">RO</option>
                  <option value="rr">RR</option>
                  <option value="rs">RS</option>
                  <option value="to">TO</option>
                </select>
              </div>
              <br class="show-always"/>
              <input class="fs-anim-lower" id="q25" name="q25" type="text" placeholder="Digite aqui sua cidade..." required />
            </div>
          </li>
          <li data-question>
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label" for="q26">Qual o seu telefone?</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower">
              <input class="fs-anim-lower" id="q26" name="q26" type="text" placeholder="(DDD) XXXX-XXXX" required />
            </div>
          </li>
          <li data-input-trigger data-hide-next-button data-register-event="respondeu-parte-3">
            <div class="field-title fs-anim-upper">
              <div class="content-container">
                <label class="fs-field-label">Obrigado por participar. Clique em continuar para receber um e-mail com seu diagnóstico!</label>
              </div>
            </div>
            <div class="content-container fs-anim-lower">
              <a href="#" class="fs-button">Continuar</a>
            </div>
          </li>
        </ol>

      </form>
    </div>

    <div class="floating-logo">
      <img src="img/iel/logo-iel.png"/>
    </div>
  </form>

  <img id="submit-loader" src="img/iel/loader.svg">

  <!-- start Mixpanel -->
  <script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
mixpanel.init("029119b7e1fa503b52a32d240d8d5b52");</script>
  <!-- end Mixpanel -->

  <script src="js/classie.js"></script>
  <script src="js/selectFx.js"></script>
  <script src="js/vanilla-masker.min.js"></script>
  <script src="js/fullscreenForm.js"></script>
  <script>
    (function(window) {
      mixpanel.track("abriu-formulario");


      var formWrap = document.getElementById( 'fs-form-wrap' );
      var mapInput = document.getElementById('state-selection');
      var mapCheckboxes = document.querySelectorAll('.fs-map .uf input[type="checkbox"]');
      var mapAreaCheckboxes = document.querySelectorAll('.fs-map .uf-area input[type="checkbox"]');
      var phoneInput = document.getElementById("q26");
      var areas = [
        [
          "ro", "ac", "am", "pa", "ap", "rr", "to",
          "ba", "pi", "se", "al", "pe", "pb", "rn", "ce", "ma",
          "ms", "go", "df", "mt",
          "sp", "mg", "rj", "es",
          "pr", "sc", "rs"
        ],
        ["ro", "ac", "am", "pa", "ap", "rr", "to"],
        ["ba", "pi", "se", "al", "pe", "pb", "rn", "ce", "ma"],
        ["ms", "go", "df", "mt"],
        ["sp", "mg", "rj", "es"],
        ["pr", "sc", "rs"]
      ];

      [].slice.call( document.querySelectorAll( 'select.cs-select' ) ).forEach( function(el) {
        new SelectFx( el, {
          stickyPlaceholder: false,
          onChange: function(val){
            document.querySelector('span.cs-placeholder').style.backgroundColor = val;
          }
        });
      });

      [].slice.call(mapCheckboxes).forEach(function(el) {
        el.addEventListener('change', function() {
          toggleMapState(el.value)
        });
      });

      [].slice.call(mapAreaCheckboxes).forEach(function(el) {
        el.addEventListener('change', function() {
          toggleMapStateArea(el.value, !el.checked)
        });
      });

      function toggleMapState(state) {
        var states = mapInput.value;
        var stateIndex = states.indexOf(state);

        if (stateIndex == -1) {
          states += (states.length) ? ',' + state : state;
        } else {
          states = states.replace(state, '');
          states = states.replace(',' + state, '');
          states = states.replace(state + ',', '');
        }

        mapInput.value = states;

        checkToggleMapAreas()
      }

      function checkToggleMapAreas() {
        var checkedStates = mapInput.value;

        for (var i = 0; i < areas.length; i++) {
          var area = areas[i];
          var areaChecked = true;

          for (var j = 0; j < area.length; j++) {
            var state = areas[i][j];
            if (checkedStates.indexOf(state) == -1) {
              areaChecked = false;
              break;
            }
          }

          var id = ("tp-" + i);
          var checkbox = document.getElementById(id);
          checkbox.checked = areaChecked;

          id = ("tp-" + (i + 6));
          checkbox = document.getElementById(id);
          checkbox.checked = areaChecked;
        }
      }

      function toggleMapStateArea(area, checked) {
        var states = mapInput.value;

        for (var i = 0; i < areas[area].length; i++) {
          var state = areas[area][i];
          var element = document.querySelector('input[value="' + state + '"]')

          if (!checked) {
            states += (states.length) ? ',' + state : state;
            if (window.highlightMapArea) {
              window.highlightMapArea(state);
            }
            element.checked = true
          } else {
            states = states.replace(',' + state, '');
            states = states.replace(state + ',', '');
            states = states.replace(state, '');
            if (window.unhighlightMapArea) {
              window.unhighlightMapArea(state);
            }
            element.checked = false
          }
        }

        mapInput.value = states;
        checkToggleMapAreas()
      }

      new FForm(formWrap, {
        ctrlNavDots: false,
        onReview : function() {
          document.getElementById('submit-loader').className = 'visible';
          document.getElementById('main-form').submit();
        }
      });

      VMasker(phoneInput).maskPattern("(99) 99999-9999");
      window.onEmbedMapClick = toggleMapState;
    })(window);
  </script>

</body>
</html>
