<html>
  <head>
    <title>Inovação IEL</title>
  </head>
  <body>
    <h1>Inovação IEL: Login</h1>
    <hr/>
    <form action="#" method="POST">
      <label>Usuário</label>
      <input type="text" name="username" />
      <br />
      <label>Senha</label>
      <input type="password" name="password" />
      <br />
      <input type="submit" value="Entrar">
    </form>

    <?= $flashText ?>
  </body>
</html>
