<?php
  $innovativenessNames = [
    'APRENDIZAGEM ORGANIZACIONAL',
    'LIDERANÇA COMPROMETIDA COM A INOVAÇÃO ',
    'CULTURA DE INOVAÇÃO',
    'MARKETING PARA INOVAÇÃO',
    'ESTRATÉGIA ORIENTADA À INOVAÇÃO',
    'PESSOAS ORIENTADAS À INOVAÇÃO',
    'ESTRUTURA FAVORÁVEL À INOVAÇÃO',
    'PROCESSOS HABILITADORES DA INOVAÇÃO',
    'RECURSOS FINANCEIROS DISPONÍVEIS P/ INOVAÇÃO',
    'RELAÇÃO COM O AMBIENTE EXTERNO'
  ];
?>

<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, target-densitydpi=device-dpi, user-scalable=no">
    <title>Pesquisa de Inovação IEL</title>

    <link rel="stylesheet" type="text/css" href="/css/normalize.css" />
    <link rel="stylesheet" type="text/css" href="/css/foundation.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/demo.css" />
    <link rel="stylesheet" type="text/css" href="/css/relatorio.css" />
    <link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css" />
    <script src="/js/modernizr.custom.js"></script>
  </head>

  <style type="text/css">
    @media only screen and (min-width: 64.063em) and (max-width: 90em) {
      body {
        background: #333;
      }
    }
  </style>

  <body>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-88744224-1', 'auto');
      ga('send', 'pageview');
    </script>

    <div class="social-share-buttons">
      <a class="facebook button" target="_new" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode(siteUrl()); ?>"></a>
      <a class="linkedin button" target="_new" href="https://www.linkedin.com/cws/share?url=<?php echo urlencode(siteUrl()); ?>"></a>
      <a class="email button" id="share-email" href="#"></a>
    </div>

    <div class="share-modal" id="share-modal" style="display: none" data-equalizer-watch>
      <div id="share-form-container">
        <div id="share-form-email-sent" style="display: none; margin-bottom: 5px">
          <strong>Indicação enviada!</strong>
        </div>

        <p class="semi-bold">
          Pensou em alguém que gostaria de responder esse formulário?
        </p>

        <form id="share-form">
          <input name="name" class="fs-fields share-email-field" type="text" required placeholder="Nome" />
          <input name="email" class="fs-fields share-email-field" type="email" required placeholder="Email" />
          <input name="referer" type="hidden" value="<?php echo htmlspecialchars($referer) ?>" />

          <input class="submit-primary" type="submit" value="Enviar Convite"/>
        </form>
      </div>

      <div id="share-form-load" style="display: none">
        <img src="/img/iel/loader.svg">
      </div>
    </div>

    <div class="container">
      <div id="first-title" class="row title ">
        <div class="small-12 large-4 medium-12 columns text-center">
          <img src="/img/iel/relatorio/logo.png" id="logo-medium" class="show-for-medium" />
          <img src="/img/iel/logo-inovacao.png" id="logo-small-only" class="show-for-small-only " />
        </div>

        <div class="small-12 large-6 medium-12 columns" id="title-label">
          <h1>SUA CAPACIDADE</h1>
          <h2>DE GESTÃO DA INOVAÇÃO</h2>
          <h3><?= $generalInnovationScore ?></h3>
        </div>
      </div>

      <section class="row expanded light-background" id="graph">
        <div class="small-12 large-3 medium-4 columns sidebar show-for-small-only" style="padding:30px">
          <div class="row">
            <div class="columns text-left">
              <h1 class="sidebar-title">A</h1>
            </div>
            <div class="small-7 large-7 columns">
              <h6 class="sidebar-subtitle text-right">Experiência Gestão da Inovação</h6>
            </div>
          <div>
            <div class="small-12 large-12 columns">
              <p class="sidebar-description text-left" style="padding-left:0px">
                Sua capacidade de inovação é composta por duas análises: O estado das PRÁTICAS INTERNAS de inovação e os RESULTADOS obtidos com a inovação.
              </p>
            </div>
          </div>
          </div>


        </div>
        <div class="large-8 medium-8 small-12 columns ">
          <div class="general-graph-container">
            <div class="general-graph-virtual-area">
              <div class="general-graph-pointer" style="left: <?= $xAxisValue ?>%; bottom: <?= $yAxisValue ?>%;">
              </div>
            </div>
            <a href="#book-a-visit">
              <img src="/img/iel/relatorio/grafico.png" />
            </a>
            <img src="/img/iel/relatorio/grafico-top.png" class="general-graph-top" />
          </div>

          <br/>
        </div>
        <div class="small-12 large-4 medium-4 columns sidebar show-for-medium">
          <div class="row new-title-header">
            <div class="columns text-left" style="padding-left:0px">
              <h1 class="sidebar-title">A</h1>
            </div>
            <div class="small-7 large-7 columns">
              <h6 class="sidebar-subtitle text-right">Experiência em Gestão da Inovação</h6>
            </div>
          </div>
          <div>
            <div class="small-12 large-12 columns">
              <p class="sidebar-description text-left" style="padding-left:0px">
                Sua capacidade de inovação é composta por duas análises: O estado das PRÁTICAS INTERNAS de inovação e os RESULTADOS obtidos com a inovação.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section class="row expanded" >
        <div class="small-12 medium-10 medium-offset-1 large-8 large-offset-2 columns">
          <p id="graph-description" class="text-center text-justify-mobile">
            <?php if (($xAxisValue >= 66) && ($yAxisValue >= 66)): ?>
              De acordo com as respostas, sua empresa apresenta <strong>boa pontuação (acima de 66%)</strong>
              em suas práticas fundamentais de inovação e <strong>alta pontuação (acima de 66%)</strong> nos
              itens de resultados de inovação o que sinaliza que a empresa está no caminho certo da inovação,
              parabéns! <strong>Veja abaixo os destaques das sua avaliação.</strong>
            <?php elseif (($xAxisValue < 66) && ($yAxisValue < 66)): ?>
              De acordo com as respostas, sua empresa apresenta <strong>baixa/média pontuação (abaixo de 66%)</strong>
              em suas práticas fundamentais de inovação e <strong>baixa/média pontuação (abaixo de 66%)</strong> nos
              itens de resultados de inovação. Este cenário e considerado o mais comum no universo de empresas,
              no qual, de modo objetivo, não existe um contexto interno favorável à inovação e isso fatalmente
              resulta na falta (ou baixo fluxo) de soluções inovadoras indo ao mercado. <strong>Veja abaixo os
              destaques das sua avaliação.</strong>
            <?php elseif (($xAxisValue >= 66) && ($yAxisValue < 66)): ?>
              De acordo com suas respostas, sua empresa apresenta <strong>boa pontuação (acima de 66%) em suas  práticas
              internas de inovação</strong>, o que geralmente habilita com que inovações surjam e sejam  transformadas
              efetivamente em projetos e, quem sabe, em inovação real para o negócio. No entanto, sua empresa
              <strong>obteve baixa/média pontuação (abaixo de 66%) nos itens de resultados de inovação.</strong> Algumas
              são as explicações para este cenário, mas, de modo amplo há barreiras internas que estão impedindo que uma
              aparente cultura inovadora interna gere resultados concretos.
            <?php elseif (($xAxisValue < 66) && ($yAxisValue >= 66)): ?>
              De acordo com as respostas, sua empresa apresenta <strong>baixa/média pontuação (abaixo de 66%)</strong>
              em suas práticas fundamentais de inovação e <strong>alta pontuação (acima de 66%)</strong> nos itens
              de resultados de inovação. Este caso ocorre, em geral, quando as inovações geradas nos últimos tempos
              são advindas de oportunidades de mercado pontuais, por esforço efêmero (curta duração) da equipe ou
              qualquer outra situação de mercado favorável. Este cenário - baixa/média capacidade, altos resultados - é
              raro e pode se esperar que ele não seja duradouro, não havendo sustentação da inovação na empresa por
              meio de processos sistemáticos de inovação. <strong>Veja abaixo os destaques das sua avaliação.</strong>
            <?php endif; ?>
          </p>
        </div>
      </section>

      <section class="row expanded b-area" >

        <div class="small-12 columns sidebar show-for-small-only">
          <div class="row">
            <div class="columns text-left">
              <h1 class="sidebar-title">B</h1>
            </div>
            <div class="small-7 large-7 columns">
              <h6 class="sidebar-subtitle text-right">Análise dos tipos de inovação</h6>
            </div>
          </div>
          <div class="row">
            <div class="small-12 large-12 columns">
              <p class="sidebar-description text-left">
                Você prioriza atualmente a inovação
                  <?php
                    switch ($innovationPriorityIndex) {
                      case 0: echo 'em <strong>PRODUTOS</strong>'; break;
                      case 1: echo 'em <strong>PROCESSOS</strong>'; break;
                      case 2: echo 'em <strong>MARKETING</strong>'; break;
                      case 3: echo '<strong>ORGANIZACIONAL</strong>'; break;
                    }
                  ?>.
                Seu score nos resultados com esse tipo de inovação ficou em <strong>
                <?= $innovationTypesScores[$innovationPriorityIndex] ?>% (<?= $innovationTypesScores[$innovationPriorityIndex] < 70 ? 'baixo' : 'alto' ?>)</strong>
              </p>
            </div>
          </div>
        </div>

        <div class="medium-8 large-8 small-12 columns " style="padding-top:0px" id="progresses">
          <div class="row progress-indicator">
            <div class="small-4 large-4 columns progress-title" style="text-align:center">
              <div class="progress-label">
                <span>Inovação em</span> <strong>Produtos</strong>
              </div>
              <div class="progress-icon <?= ($innovationPriorityIndex == 0) ? 'with-border' : '' ?>">
                <i class="fa fa-rocket" aria-hidden="true"></i>
              </div>
            </div>
            <div class="small-8 large-8 columns">
              <div class="progress-bar-container">
                <div class="progress-bar <?= ($innovationPriorityIndex == 0) ? 'danger' : '' ?>" style="width: <?= $innovationTypesScores[0] ?>%">
                  <?php
                    if ($innovationTypesScores[0] < 33) {
                      echo 'BAIXO';
                    } elseif ($innovationTypesScores[0] < 66) {
                      echo 'MÉDIO';
                    } else {
                      echo 'ALTO';
                    }
                  ?>
                </div>

                <p class="progress-description">
                  Inovação que gera novas soluções (produtos, serviços ou sua
                  combinação) a serem ofertadas ao mercado.
                </p>
              </div>
            </div>
          </div>

          <div class="row progress-indicator">
            <div class="small-4 large-4 columns progress-title" style="text-align:center">
              <div class="progress-label">
                <span>Inovação em</span> <strong>Processos</strong>
              </div>
              <div class="progress-icon <?= ($innovationPriorityIndex == 1) ? 'with-border' : '' ?>">
                <i class="fa fa-recycle" aria-hidden="true"></i>
              </div>
            </div>
            <div class="small-8 large-8 columns">
              <div class="progress-bar-container">
                <div class="progress-bar <?= ($innovationPriorityIndex == 1) ? 'danger' : '' ?>" style="width: <?= $innovationTypesScores[1] ?>%">
                  <?php
                    if ($innovationTypesScores[1] < 33) {
                      echo 'BAIXO';
                    } elseif ($innovationTypesScores[1] < 66) {
                      echo 'MÉDIO';
                    } else {
                      echo 'ALTO';
                    }
                  ?>
                </div>

                <p class="progress-description">
                  Inovação que otimiza processos para aumento da rapidez de
                  processamento, da flexibilidade da qualidade dos outputs, da
                  velocidade a atendimento à demandas de clientes, etc.
                </p>
              </div>
            </div>
          </div>

          <div class="row progress-indicator">
            <div class="small-4 large-4 columns progress-title" style="text-align:center">
              <div class="progress-label">
                <span>Inovação em</span> <strong>Marketing</strong>
              </div>
              <div class="progress-icon <?= ($innovationPriorityIndex == 2) ? 'with-border' : '' ?>">
                <i class="fa fa-bullhorn" aria-hidden="true"></i>
              </div>
            </div>
            <div class="small-8 large-8 columns">
              <div class="progress-bar-container">
                <div class="progress-bar <?= ($innovationPriorityIndex == 2) ? 'danger' : '' ?>" style="width: <?= $innovationTypesScores[2] ?>%">
                  <?php
                    if ($innovationTypesScores[2] < 33) {
                      echo 'BAIXO';
                    } elseif ($innovationTypesScores[2] < 66) {
                      echo 'MÉDIO';
                    } else {
                      echo 'ALTO';
                    }
                  ?>
                </div>

                <p class="progress-description">
                  Inovação que redefine os canais e formatos de relacionamento com
                  clientes, além de criar novas formas de engajamento com o
                  público de interesse.
                </p>
              </div>
            </div>
          </div>

          <div class="row progress-indicator">
            <div class="small-4 large-4 columns progress-title" style="text-align:center">
              <div class="progress-label">
                <span>Inovação</span> <strong>Organizacional</strong>
              </div>
              <div class="progress-icon <?= ($innovationPriorityIndex == 3) ? 'with-border' : '' ?>">
                <i class="fa fa-cubes" aria-hidden="true"></i>
              </div>
            </div>
            <div class="small-8 large-8 columns">
              <div class="progress-bar-container">
                <div class="progress-bar <?= ($innovationPriorityIndex == 3) ? 'danger' : '' ?>" style="width: <?= $innovationTypesScores[3] ?>%">
                  <?php
                    if ($innovationTypesScores[3] < 33) {
                      echo 'BAIXO';
                    } elseif ($innovationTypesScores[3] < 66) {
                      echo 'MÉDIO';
                    } else {
                      echo 'ALTO';
                    }
                  ?>
                </div>

                <p class="progress-description">
                  Inovação que cria novos arranjos de estrutura, de comunicação
                  interna, de resolução de conflitos, de recompensa, de
                  planejamento de estratégias e ações diárias, entre outras.
                </p>
              </div>
            </div>
          </div>

        </div>
        <div class="small-3 large-4 medium-4 columns sidebar show-for-medium">
          <div class="row new-title-header">
            <div class="columns text-left" style="padding:0px">
              <h1 class="sidebar-title">B</h1>
            </div>
            <div class="small-7 large-7 medium-7 columns">
              <h6 class="sidebar-subtitle text-right">Análise dos tipos de inovação</h6>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-12 large-12 columns">
              <p class="sidebar-description text-left">
                Você prioriza atualmente a inovação
                  <?php
                    switch ($innovationPriorityIndex) {
                      case 0: echo 'em <strong>PRODUTOS</strong>'; break;
                      case 1: echo 'em <strong>PROCESSOS</strong>'; break;
                      case 2: echo 'em <strong>MARKETING</strong>'; break;
                      case 3: echo '<strong>ORGANIZACIONAL</strong>'; break;
                    }
                  ?>.
                Seu score nos resultados com esse tipo de inovação ficou em <strong>
                <?= $innovationTypesScores[$innovationPriorityIndex] ?>% (<?= $innovationTypesScores[$innovationPriorityIndex] < 70 ? 'baixo' : 'alto' ?>)</strong>
              </p>
            </div>
          </div>
        </div>
      </section>

      <section class="row expanded light-background" style="padding-top:30px">
        <div class="small-12 large-3 columns sidebar  hide-for-medium">
          <div class="row">
            <div class="columns text-left">
              <h1 class="sidebar-title">C</h1>
            </div>
            <div class="small-7 large-7 columns">
              <h3 class="sidebar-subtitle text-right">Análise da capacidade de inovação</h3>
            </div>
          </div>
          <div class="row">
            <div class="small-12 large-12 columns">
              <p class="sidebar-description text-left">
                Veja a classificação da organização em relação a cada um dos fundamentos
                essenciais à inovação.
              </p>
              <p class="sidebar-description text-left">
                <?php
                  $first = true;
                  for ($i = 0; $i < 10; $i++) {
                    $innovativenessScore = $innovativenessScores[$i];
                    if ($innovativenessScore >= 66) {
                      if ($first) {
                        echo '<img src="/img/iel/relatorio/hands-05.png" width="48px"/>';
                        $first = false;
                      }
                      echo '<span class="innovativeness-description">' . $innovativenessNames[$i] . '</span>';
                    }
                  }
                ?>

                <?php
                  $first = true;
                  for ($i = 0; $i < 10; $i++) {
                    $innovativenessScore = $innovativenessScores[$i];
                    if ($innovativenessScore < 33) {
                      if ($first) {
                        echo '<img src="/img/iel/relatorio/hands-06.png" width="48px"/>';
                        $first = false;
                      }
                      echo '<span class="innovativeness-description">' . $innovativenessNames[$i] . '</span>';
                    }
                  }
                ?>
              </p>
            </div>
          </div>
        </div>
        <div class="small-12 medium-8 large-8 columns " id="graphs" >
          <div class="row">
            <div class="small-6 large-6 medium-6 columns">
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-2 large-3 large-order-1 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span>
                      <?php
                        if ($innovativenessScores[0] < 33) {
                          echo 'BAIXO';
                        } elseif ($innovativenessScores[0] < 66) {
                          echo 'MÉDIO';
                        } else {
                          echo 'ALTO';
                        }
                      ?>
                    </span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
                <div class="small-12 medium-12 small-order-3 large-5 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[0] ?>" <?= ($innovativenessScores[0] >= 66) ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-1 large-4 large-order-3 columns graph-title">
                  <span>Aprendizagem Organizacional  (<?php
                      if ($innovativenessScores[0] < 33) {
                        echo 'BAIXO';
                      } elseif ($innovativenessScores[0] < 66) {
                        echo 'MÉDIO';
                      } else {
                        echo 'ALTO';
                      }
                    ?>)</span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-2 large-3 large-order-1 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span>
                      <?php
                        if ($innovativenessScores[2] < 33) {
                          echo 'BAIXO';
                        } elseif ($innovativenessScores[2] < 66) {
                          echo 'MÉDIO';
                        } else {
                          echo 'ALTO';
                        }
                      ?>
                    </span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
                <div class="small-12 medium-12 small-order-3 large-5 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[2] ?>" <?= ($innovativenessScores[2] >= 66) ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-1 large-4 large-order-3 columns graph-title">
                  <span>Cultura de Inovação (<?php
                      if ($innovativenessScores[2] < 33) {
                        echo 'BAIXO';
                      } elseif ($innovativenessScores[2] < 66) {
                        echo 'MÉDIO';
                      } else {
                        echo 'ALTO';
                      }
                    ?>)</span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-2 large-3  large-order-1  columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span>
                      <?php
                        if ($innovativenessScores[4] < 33) {
                          echo 'BAIXO';
                        } elseif ($innovativenessScores[4] < 66) {
                          echo 'MÉDIO';
                        } else {
                          echo 'ALTO';
                        }
                      ?>
                    </span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
                <div class="small-12 medium-12 small-order-3 large-5  large-order-2  columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[4] ?>" <?= ($innovativenessScores[4] >= 66) ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-1 large-4  large-order-3  columns graph-title">
                  <span>Estratégia Orientada à Inovação  (<?php
                      if ($innovativenessScores[4] < 33) {
                        echo 'BAIXO';
                      } elseif ($innovativenessScores[4] < 66) {
                        echo 'MÉDIO';
                      } else {
                        echo 'ALTO';
                      }
                    ?>)</span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-2 large-3  large-order-1  columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span>
                      <?php
                        if ($innovativenessScores[6] < 33) {
                          echo 'BAIXO';
                        } elseif ($innovativenessScores[6] < 66) {
                          echo 'MÉDIO';
                        } else {
                          echo 'ALTO';
                        }
                      ?>
                    </span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
                <div class="small-12 medium-12 small-order-3 large-5  large-order-2  columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[6] ?>" <?= ($innovativenessScores[6] >= 66) ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-1 large-4  large-order-3  columns graph-title">
                  <span>Estrutura Favorável à Inovação  (<?php
                      if ($innovativenessScores[6] < 33) {
                        echo 'BAIXO';
                      } elseif ($innovativenessScores[6] < 66) {
                        echo 'MÉDIO';
                      } else {
                        echo 'ALTO';
                      }
                    ?>)</span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-2 large-3  large-order-1  columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span>
                      <?php
                        if ($innovativenessScores[8] < 33) {
                          echo 'BAIXO';
                        } elseif ($innovativenessScores[8] < 66) {
                          echo 'MÉDIO';
                        } else {
                          echo 'ALTO';
                        }
                      ?>
                    </span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
                <div class="small-12 medium-12 small-order-3 large-5  large-order-2  columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[8] ?>" <?= ($innovativenessScores[8] >= 66) ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-1 large-4  large-order-3  columns graph-title">
                  <span>Recursos Financeiros disponíveis p/ Inovação  (<?php
                      if ($innovativenessScores[8] < 33) {
                        echo 'BAIXO';
                      } elseif ($innovativenessScores[8] < 66) {
                        echo 'MÉDIO';
                      } else {
                        echo 'ALTO';
                      }
                    ?>)</span>
                </div>
              </div>
            </div>

            <div class="small-6 large-6 medium-6 columns text-right">
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-1 large-5 large-order-1 columns graph-title">
                  <span>Liderança Comprometida com a Inovação  (<?php
                      if ($innovativenessScores[1] < 33) {
                        echo 'BAIXO';
                      } elseif ($innovativenessScores[1] < 66) {
                        echo 'MÉDIO';
                      } else {
                        echo 'ALTO';
                      }
                    ?>)</span>
                </div>
                <div class="small-12 medium-12 small-order-2 large-4 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[1] ?>" <?= ($innovativenessScores[1] >= 66) ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-2 large-3 large-order-3 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span>
                      <?php
                        if ($innovativenessScores[1] < 33) {
                          echo 'BAIXO';
                        } elseif ($innovativenessScores[1] < 66) {
                          echo 'MÉDIO';
                        } else {
                          echo 'ALTO';
                        }
                      ?>
                    </span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-1 large-5 large-order-1 columns graph-title">
                  <span>Marketing para Inovação  (<?php
                      if ($innovativenessScores[3] < 33) {
                        echo 'BAIXO';
                      } elseif ($innovativenessScores[3] < 66) {
                        echo 'MÉDIO';
                      } else {
                        echo 'ALTO';
                      }
                    ?>)</span>
                </div>
                <div class="small-12 medium-12 small-order-2 large-4 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[3] ?>" <?= ($innovativenessScores[3] >= 66) ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-2  large-3 large-order-3 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span>
                      <?php
                        if ($innovativenessScores[3] < 33) {
                          echo 'BAIXO';
                        } elseif ($innovativenessScores[3] < 66) {
                          echo 'MÉDIO';
                        } else {
                          echo 'ALTO';
                        }
                      ?>
                    </span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-1 large-5 large-order-1 columns graph-title">
                  <span>Pessoas orientadas à Inovação  (<?php
                      if ($innovativenessScores[5] < 33) {
                        echo 'BAIXO';
                      } elseif ($innovativenessScores[5] < 66) {
                        echo 'MÉDIO';
                      } else {
                        echo 'ALTO';
                      }
                    ?>)</span>
                </div>
                <div class="small-12 medium-12 medium-order-1 small-order-2 large-4 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[5] ?>" <?= ($innovativenessScores[5] >= 66) ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-2 large-3 large-order-3 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span>
                      <?php
                        if ($innovativenessScores[5] < 33) {
                          echo 'BAIXO';
                        } elseif ($innovativenessScores[5] < 66) {
                          echo 'MÉDIO';
                        } else {
                          echo 'ALTO';
                        }
                      ?>
                    </span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-1  large-5 large-order-1 columns graph-title">
                  <span>Processos Habilitadores da Inovação  (<?php
                      if ($innovativenessScores[7] < 33) {
                        echo 'BAIXO';
                      } elseif ($innovativenessScores[7] < 66) {
                        echo 'MÉDIO';
                      } else {
                        echo 'ALTO';
                      }
                    ?>)</span>
                </div>
                <div class="small-12 medium-12 small-order-2 large-4 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[7] ?>" <?= ($innovativenessScores[7] >= 66) ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-2  large-3 large-order-3 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span>
                      <?php
                        if ($innovativenessScores[7] < 33) {
                          echo 'BAIXO';
                        } elseif ($innovativenessScores[7] < 66) {
                          echo 'MÉDIO';
                        } else {
                          echo 'ALTO';
                        }
                      ?>
                    </span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-1  large-5 large-order-1 columns graph-title">
                  <span>Relação com o ambiente externo  (<?php
                      if ($innovativenessScores[9] < 33) {
                        echo 'BAIXO';
                      } elseif ($innovativenessScores[9] < 66) {
                        echo 'MÉDIO';
                      } else {
                        echo 'ALTO';
                      }
                    ?>)</span>
                </div>
                <div class="small-12 medium-12 small-order-2 large-4 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[9] ?>" <?= ($innovativenessScores[9] >= 66) ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-2 large-3 large-order-3 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span>
                      <?php
                        if ($innovativenessScores[9] < 33) {
                          echo 'BAIXO';
                        } elseif ($innovativenessScores[9] < 66) {
                          echo 'MÉDIO';
                        } else {
                          echo 'ALTO';
                        }
                      ?>
                    </span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
              </div>
            </div>

          </div>
        </div>
        <div class="small-3 medium-4 large-4 columns sidebar show-for-medium">
          <div class="row new-title-header">
            <div class="columns text-left" style="padding-left:0px">
              <h1 class="sidebar-title">C</h1>
            </div>
            <div class="small-7 large-7 columns">
              <h3 class="sidebar-subtitle text-right">Análise da capacidade de inovação</h3>
            </div>
          </div>
          <div class="row">
            <div class="small-12 large-12 columns">
              <p class="sidebar-description text-left">
                Veja a classificação da organização em relação a cada um dos fundamentos
                essenciais à inovação.
              </p>
              <p class="sidebar-description text-left">
                <?php
                  $first = true;
                  for ($i = 0; $i < 10; $i++) {
                    $innovativenessScore = $innovativenessScores[$i];
                    if ($innovativenessScore >= 66) {
                      if ($first) {
                        echo '<img src="/img/iel/relatorio/hands-05.png" width="48px"/>';
                        $first = false;
                      }
                      echo '<span class="innovativeness-description">' . $innovativenessNames[$i] . '</span>';
                    }
                  }
                ?>

                <?php
                  $first = true;
                  for ($i = 0; $i < 10; $i++) {
                    $innovativenessScore = $innovativenessScores[$i];
                    if ($innovativenessScore < 33) {
                      if ($first) {
                        echo '<img src="/img/iel/relatorio/hands-06.png" width="48px"/>';
                        $first = false;
                      }
                      echo '<span class="innovativeness-description">' . $innovativenessNames[$i] . '</span>';
                    }
                  }
                ?>
              </p>
            </div>
          </div>
        </div>


      </section>

      <section class="row expanded" id="solutions">
        <div class="small-12 large-5 medium-10 medium-offset-1 large-offset-0 columns text-justify" id="solutions-title">
          <h1>Conheça</h1>
          <h2>As soluções em gestão da</h2>
          <h3><strong>Inovação <em>IEL</em></strong></h3>
          <p style="text-transform:none">
            O IEL entrega soluções que aumentarão a capacidade de sua empresa em
            inovar. Somos a <strong>única</strong> consultoria a atender em todo o
            país com uma oferta completa em inovação.
          </p>
        </div>
      </section>

      <section class="row" id="solutions-graph" >
        <div class="columns small-12">
          <img src="/img/iel/relatorio/solucoes.png" class="hide-for-small-only"/>
        </div>
      </section>

      <section class="row collapse" id="solutions-boxes" data-equalizer>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Mapeamento da Gestão da Inovação
            </div>
            <div class="solution-box-body">
              Diagnóstico para identificação e tratamento de barreiras à inovação e embasamento das soluções aplicáveis.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Sensibilização Interna
            </div>
            <div class="solution-box-body">
              Ponto de partida pré-intervenção para garantia de apoio de pessoal  interno chave e outros stakeholders.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Política e Estratégia de Inovação
            </div>
            <div class="solution-box-body">
              Definição do direcionamento estratégico e das expectativas da empresa com a adoção das práticas de Gestão da Inovação, baseando-se em forças de mudanças mercadológicas, sociais e tecnológicas.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Gestão de Ideias
            </div>
            <div class="solution-box-body">
              Promoção à participação e contribuição da força de trabalho nas atividades inovativas da empresa e estruturação do processo de ideação e geração de ideias.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Projetos de Inovação
            </div>
            <div class="solution-box-body">
              Boas práticas para detalhamento dos projetos de inovação resultantes do processo sistemático de coleta de idéias ou mesmo de demandas de mercado específicas.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Medição de Resultados
            </div>
            <div class="solution-box-body">
              Organização do processo de análise da evolução das atividades inovativas e das experiências internas visando a absorção das lições aprendidas e seu compartilhamento, além de apurar indicadores de performance e resultados relacionados à inovação.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Reconhecimento e premiação
            </div>
            <div class="solution-box-body">
              Estimular o engajamento das organizações em atividades inovativas por meio de iniciativas de reconhecimento, premiação  e compartilhamento de boas práticas.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Capacitações em inovação
            </div>
            <div class="solution-box-body">
              Múltiplas ofertas de capacitações, workshops e treinamentos  em inovação,  para antes durante e depois dos projetos.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Plano de Gestão da Inovação
            </div>
            <div class="solution-box-body">
              O Plano de Gestão da Inovação é um instrumento que resume de maneira executiva os diretrizes que devem guiar as ações inovativas da empresa para aumentar sua maturidade em estabelecer seus processos de inovação sistemática.
            </div>
          </div>
        </div>
      </section>

      <?php if (isset($contacts) && ($contacts != null) && (!empty($contacts))): ?>
        <section class="row" id="book-a-visit">
          <div class="small-12 large-12 columns">
            <h1>
              <span>Agende uma visita e veja como você pode inovar mais, na</span>
              <em>prática!</em>
            </h1>

            <?php foreach ($contacts as $contact): ?>
              <h2><?= $contact->name ?></h2>
              <h3><?= $contact->email ?></h3>
              <h3><?= $contact->phone ?></h3>
            <?php endforeach; ?>
          </div>
        </section>
      <?php endif; ?>

      <section class="row expanded align-middle text-left" id="footer">
        <div class="small-12 large-3 medium-3 medium-offset-1 large-offset-1 ">
          <img src="/img/iel/relatorio/footer-inov-logo.png"/>
        </div>
        <div class="small-12 large-5 medium-5 text-center">
          <h6>www.iel.org.br/gestaodainovacao</h6>
        </div>
        <div class="small-12 large-2 medium-2 text-center">
          <img src="/img/iel/relatorio/footer-iel-logo.png"/>
        </div>
      </section>
    </div>

    <!-- Scripts -->
    <script type="text/javascript" src="/js/vendor/jquery.js"></script>
    <script type="text/javascript" src="/js/vendor/what-input.js"></script>
    <script type="text/javascript" src="/js/vendor/foundation.min.js"></script>
    <script src="/js/progressbar.js"></script>
    <script src="/js/relatorio.js"></script>
  </body>
</html>
