<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, target-densitydpi=device-dpi, user-scalable=no">
    <title>Pesquisa de Inovação IEL</title>

    <link rel="stylesheet" type="text/css" href="/css/normalize.css" />
    <link rel="stylesheet" type="text/css" href="/css/foundation.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/demo.css" />
    <link rel="stylesheet" type="text/css" href="/css/relatorio.css" />
    <link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css" />
    <script src="/js/modernizr.custom.js"></script>
  </head>

  <body class="text-center">

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-88744224-1', 'auto');
      ga('send', 'pageview');
    </script>

    <div class="container" style="height:100%;">
      <div class="row align-center">
        <div class="small-12 large-4 medium-12 columns">
          <img src="/img/iel/relatorio/logo.png" id="logo-medium" class="show-for-medium" />
          <img src="/img/iel/logo-inovacao.png" id="logo-small-only" class="show-for-small-only " />
        </div>
      </div>

      <section class="row align-center" style="margin-top: 50px">
        <div class="small-12 medium-8 columns">
          <h1><strong>Oops!</strong></h1>
          <h2>Não encontramos esse relatório no nosso banco de dados!</h2>
        </div>
      </section>
  </body>
</html>
