<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, target-densitydpi=device-dpi, user-scalable=no">
    <title>Pesquisa de Inovação IEL</title>

    <link rel="stylesheet" type="text/css" href="/css/normalize.css" />
    <link rel="stylesheet" type="text/css" href="/css/foundation.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/demo.css" />
    <link rel="stylesheet" type="text/css" href="/css/relatorio.css" />
    <link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css" />
    <script src="/js/modernizr.custom.js"></script>
  </head>

  <style type="text/css">
    @media only screen and (min-width: 64.063em) and (max-width: 90em) {
      body {
        background: #333;
      }
    }
  </style>

  <body>
    <div class="container">
      <div id="first-title" class="row title ">
        <div class="small-12 large-4 medium-12 columns text-center">
          <img src="/img/iel/relatorio/logo.png" id="logo-medium" class="show-for-medium" />
          <img src="/img/iel/logo-inovacao.png" id="logo-small-only" class="show-for-small-only " />
        </div>

        <div class="small-12 large-6 medium-12 columns" id="title-label">
          <h1>SUA CAPACIDADE</h1>
          <h2>DE GESTÃO DA INOVAÇÃO</h2>
          <h3>MÉDIA</h3>
        </div>
<!--         <div class="small-4 large-2 medium-2 columns" id="title-level-right">
          <h1 id="title-level"><?= $generalInnovationScore ?></h1>
        </div> -->
      </div>

      <section class="row expanded light-background" id="graph">
        <div class="small-12 large-3 medium-4 columns sidebar show-for-small-only">
          <div class="row">
            <div class="columns text-center">
              <h1 class="sidebar-title">A</h1>
            </div>
            <div class="small-7 large-7 columns">
              <h6 class="sidebar-subtitle text-right">Experiência Gestão da Inovação</h6>
            </div>
          </div>
        </div>
        <div class="large-8 medium-8 small-12 columns ">
          <div class="general-graph-container">
            <div class="general-graph-virtual-area">
              <div class="general-graph-pointer" style="left: <?= $xAxisValue ?>%; bottom: <?= $yAxisValue ?>%;"><?= $generalInnovationScore ?></div>
            </div>
            <img src="/img/iel/relatorio/grafico.png" />
          </div>

          <br/>
          <p id="graph-description" class="text-justify">
            <?php if (($xAxisValue >= 70) && ($yAxisValue >= 70)): ?>
              De acordo com as respostas, sua empresa apresenta <strong>boa pontuação (acima de 70%)</strong>
              em suas práticas fundamentais de inovação e <strong>alta pontuação (acima de 70%)</strong> nos
              itens de resultados de inovação o que sinaliza que a empresa está no caminho certo da inovação,
              parabéns! <strong>Veja abaixo os destaques das sua avaliação.</strong>
            <?php elseif (($xAxisValue < 70) && ($yAxisValue < 70)): ?>
              De acordo com as respostas, sua empresa apresenta <strong>baixa pontuação (abaixo de 70%)</strong>
              em suas práticas fundamentais de inovação e <strong>baixa pontuação (abaixo de 70%)</strong> nos
              itens de resultados de inovação. Este cenário e considerado o mais comum no universo de empresas,
              no qual, de modo objetivo, não existe um contexto interno favorável à inovação e isso fatalmente
              resulta na falta (ou baixo fluxo) de soluções inovadoras indo ao mercado. <strong>Veja abaixo os
              destaques das sua avaliação.</strong>
            <?php elseif (($xAxisValue >= 70) && ($yAxisValue < 70)): ?>
              De acordo com as respostas, sua empresa apresenta <strong>boa pontuação (acima de 70%)</strong>
              em suas práticas fundamentais de inovação, o que geralmente habilita com que inovações surjam e
              sejam transformadas efetivamente em projetos e, quem sabe, em inovação real para o negócio. No
              entanto, sua empresa obteve <strong>baixa pontuação (abaixo de 70%)</strong> nos itens de
              resultados de inovação. Algumas são as explicações para este cenário, mas, de modo amplo há
              barreiras internas que estão impedindo que uma aparente cultura inovadora interna gere resultados
              concretos. <strong>Veja abaixo os destaques das sua avaliação.</strong>
            <?php elseif (($xAxisValue < 70) && ($yAxisValue >= 70)): ?>
              De acordo com as respostas, sua empresa apresenta <strong>baixa pontuação (abaixo de 70%)</strong>
              em suas práticas fundamentais de inovação e <strong>alta pontuação (acima de 70%)</strong> nos itens
              de resultados de inovação. Este caso ocorre, em geral, quando as inovações geradas nos últimos tempos
              são advindas de oportunidades de mercado pontuais, por esforço efêmero (curta duração) da equipe ou
              qualquer outra situação de mercado favorável. Este cenário - baixa capacidade, altos resultados - é
              raro e pode se esperar que ele não seja duradouro, não havendo sustentação da inovação na empresa por
              meio de processos sistemáticos de inovação. <strong>Veja abaixo os destaques das sua avaliação.</strong>
            <?php endif; ?>
          </p>
        </div>
        <div class="small-12 large-4 medium-4 columns sidebar show-for-medium">
          <div class="row">
            <div class="columns text-center">
              <h1 class="sidebar-title">A</h1>
            </div>
            <div class="small-7 large-7 columns">
              <h6 class="sidebar-subtitle text-right">Experiência em Gestão da Inovação</h6>
            </div>
          </div>
        </div>
      </section>

      <section class="row expanded b-area" >

        <div class="small-12 columns sidebar show-for-small-only">
          <div class="row">
            <div class="columns text-center">
              <h1 class="sidebar-title">B</h1>
            </div>
            <div class="small-7 large-7 columns">
              <h6 class="sidebar-subtitle text-right">Análise dos tipos de inovação</h6>
            </div>
          </div>
          <div class="row">
            <div class="small-12 large-12 columns">
              <p class="sidebar-description text-justify">
                Você prioriza atualmente a inovação
                  <?php
                    switch ($innovationPriorityIndex) {
                      case 0: echo 'em <strong>PRODUTOS</strong>'; break;
                      case 1: echo 'em <strong>PROCESSOS</strong>'; break;
                      case 2: echo 'em <strong>MARKETING</strong>'; break;
                      case 3: echo '<strong>ORGANIZACIONAL</strong>'; break;
                    }
                  ?>.
                Seu score nos resultados com esse tipo de inovação ficou em <strong>
                <?= $innovationTypesScores[$innovationPriorityIndex] ?>% (<?= $innovationTypesScores[$innovationPriorityIndex] < 70 ? 'baixo' : 'alto' ?>)</strong>
              </p>
            </div>
          </div>
        </div>

        <div class="medium-8 large-8 small-12 columns " style="padding-top:20px" id="progresses">
          <div class="row progress-indicator">
            <div class="small-4 large-4 columns progress-title" style="text-align:center">
              <div class="progress-label">
                <span>Inovação em</span> <strong>Produtos</strong>
              </div>
              <div class="progress-icon <?= ($innovationPriorityIndex == 0) ? 'with-border' : '' ?>">
                <i class="fa fa-rocket" aria-hidden="true"></i>
              </div>
            </div>
            <div class="small-8 large-8 columns">
              <div class="progress-bar-container">
                <div class="progress-bar <?= ($innovationPriorityIndex == 0) ? 'danger' : '' ?>" style="width: <?= $innovationTypesScores[0] ?>%">
                  <?= $innovationTypesScores[0] ?>%
                </div>

                <p class="progress-description">
                  Inovação que gera novas soluções (produtos, serviços ou sua
                  combinação) a serem ofertadas ao mercado.
                </p>
              </div>
            </div>
          </div>

          <div class="row progress-indicator">
            <div class="small-4 large-4 columns progress-title" style="text-align:center">
              <div class="progress-label">
                <span>Inovação em</span> <strong>Processos</strong>
              </div>
              <div class="progress-icon <?= ($innovationPriorityIndex == 1) ? 'with-border' : '' ?>">
                <i class="fa fa-recycle" aria-hidden="true"></i>
              </div>
            </div>
            <div class="small-8 large-8 columns">
              <div class="progress-bar-container">
                <div class="progress-bar <?= ($innovationPriorityIndex == 1) ? 'danger' : '' ?>" style="width: <?= $innovationTypesScores[1] ?>%">
                  <?= $innovationTypesScores[1] ?>%
                </div>

                <p class="progress-description">
                  Inovação que otimiza processos para aumento da rapidez de
                  processamento, da flexibilidade da qualidade dos outputs, da
                  velocidade a atendimento à demandas de clientes, etc.
                </p>
              </div>
            </div>
          </div>

          <div class="row progress-indicator">
            <div class="small-4 large-4 columns progress-title" style="text-align:center">
              <div class="progress-label">
                <span>Inovação em</span> <strong>Marketing</strong>
              </div>
              <div class="progress-icon <?= ($innovationPriorityIndex == 2) ? 'with-border' : '' ?>">
                <i class="fa fa-bullhorn" aria-hidden="true"></i>
              </div>
            </div>
            <div class="small-8 large-8 columns">
              <div class="progress-bar-container">
                <div class="progress-bar <?= ($innovationPriorityIndex == 2) ? 'danger' : '' ?>" style="width: <?= $innovationTypesScores[2] ?>%">
                  <?= $innovationTypesScores[2] ?>%
                </div>

                <p class="progress-description">
                  Inovação que redefine os canais e formatos de relacionamento com
                  clientes, além de criar novas formas de engajamento com o
                  público de interesse.
                </p>
              </div>
            </div>
          </div>

          <div class="row progress-indicator">
            <div class="small-4 large-4 columns progress-title" style="text-align:center">
              <div class="progress-label">
                <span>Inovação</span> <strong>Organizacional</strong>
              </div>
              <div class="progress-icon <?= ($innovationPriorityIndex == 3) ? 'with-border' : '' ?>">
                <i class="fa fa-cubes" aria-hidden="true"></i>
              </div>
            </div>
            <div class="small-8 large-8 columns">
              <div class="progress-bar-container">
                <div class="progress-bar <?= ($innovationPriorityIndex == 3) ? 'danger' : '' ?>" style="width: <?= $innovationTypesScores[3] ?>%">
                  <?= $innovationTypesScores[3] ?>%
                </div>

                <p class="progress-description">
                  Inovação que cria novos arranjos de estrutura, de comunicação
                  interna, de resolução de conflitos, de recompensa, de
                  planejamento de estratégias e ações diárias, entre outras.
                </p>
              </div>
            </div>
          </div>

        </div>
        <div class="small-3 large-4 medium-4 columns sidebar show-for-medium">
          <div class="row">
            <div class="columns text-center">
              <h1 class="sidebar-title">B</h1>
            </div>
            <div class="small-7 large-7 medium-7 columns">
              <h6 class="sidebar-subtitle text-right">Análise dos tipos de inovação</h6>
            </div>
          </div>
          <div class="row">
            <div class="small-12 medium-12 large-12 columns">
              <p class="sidebar-description text-justify">
                Você prioriza atualmente a inovação
                  <?php
                    switch ($innovationPriorityIndex) {
                      case 0: echo 'em <strong>PRODUTOS</strong>'; break;
                      case 1: echo 'em <strong>PROCESSOS</strong>'; break;
                      case 2: echo 'em <strong>MARKETING</strong>'; break;
                      case 3: echo '<strong>ORGANIZACIONAL</strong>'; break;
                    }
                  ?>.
                Seu score nos resultados com esse tipo de inovação ficou em <strong>
                <?= $innovationTypesScores[$innovationPriorityIndex] ?>% (<?= $innovationTypesScores[$innovationPriorityIndex] < 70 ? 'baixo' : 'alto' ?>)</strong>
              </p>
            </div>
          </div>
        </div>

      </section>

      <section class="row expanded light-background">
        <div class="small-12 large-3 columns sidebar  hide-for-medium">
          <div class="row">
            <div class="columns text-center">
              <h1 class="sidebar-title">C</h1>
            </div>
            <div class="small-7 large-7 columns">
              <h3 class="sidebar-subtitle text-right">Análise da capacidade de inovação</h3>
            </div>
          </div>
          <div class="row">
            <div class="small-12 large-12 columns">
              <p class="sidebar-description text-justify">
                Veja a classificação da organização em relação a cada um dos fundamentos
                essenciais à inovação.
              </p>
              <p class="sidebar-description text-justify">
                Maior escore: <strong>
                <?php
                  switch ($highestInnovativenessScoreIndex) {
                  case 0: echo 'APRENDIZAGEM ORGANIZACIONAL'; break;
                  case 1: echo 'LIDERANÇA COMPROMETIDA COM A INOVAÇÃO '; break;
                  case 2: echo 'CULTURA DE INOVAÇÃO'; break;
                  case 3: echo 'MARKETING PARA INOVAÇÃO'; break;
                  case 4: echo 'ESTRATÉGIA ORIENTADA À INOVAÇÃO'; break;
                  case 5: echo 'PESSOAS ORIENTADAS À INOVAÇÃO'; break;
                  case 6: echo 'ESTRUTURA FAVORÁVEL À INOVAÇÃO'; break;
                  case 7: echo 'PROCESSOS HABILITADORES DA INOVAÇÃO'; break;
                  case 8: echo 'RECURSOS FINANCEIROS DISPONÍVEIS P/ INOVAÇÃO'; break;
                  case 9: echo 'RELAÇÃO COM O AMBIENTE EXTERNO'; break;
                  };
                ?>
                </strong>
              </p>
            </div>
          </div>
        </div>
        <div class="small-12 medium-8 large-8 columns " id="graphs">
          <div class="row">
            <div class="small-6 large-6 medium-6 columns">
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-2 large-3 large-order-1 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span><?= $innovativenessScores[0] ?>%</span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
                <div class="small-12 medium-12 small-order-3 large-5 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[0] ?>" <?= $highestInnovativenessScoreIndex == 0 ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-1 large-4 large-order-3 columns graph-title">
                  <span>Aprendizagem Organizacional (<?= $innovativenessScores[0] ?>%)</span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-2 large-3 large-order-1 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span><?= $innovativenessScores[2] ?>%</span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
                <div class="small-12 medium-12 small-order-3 large-5 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[2] ?>" <?= $highestInnovativenessScoreIndex == 2 ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-1 large-4 large-order-3 columns graph-title">
                  <span>Cultura de Inovação(<?= $innovativenessScores[2] ?>%)</span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-2 large-3  large-order-1  columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span><?= $innovativenessScores[4] ?>%</span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
                <div class="small-12 medium-12 small-order-3 large-5  large-order-2  columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[4] ?>" <?= $highestInnovativenessScoreIndex == 4 ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-1 large-4  large-order-3  columns graph-title">
                  <span>Estratégia Orientada à Inovação (<?= $innovativenessScores[4] ?>%)</span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-2 large-3  large-order-1  columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span><?= $innovativenessScores[6] ?>%</span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
                <div class="small-12 medium-12 small-order-3 large-5  large-order-2  columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[6] ?>" <?= $highestInnovativenessScoreIndex == 6 ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-1 large-4  large-order-3  columns graph-title">
                  <span>Estrutura Favorável à Inovação (<?= $innovativenessScores[6] ?>%)</span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-2 large-3  large-order-1  columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span><?= $innovativenessScores[8] ?>%</span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
                <div class="small-12 medium-12 small-order-3 large-5  large-order-2  columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[8] ?>" <?= $highestInnovativenessScoreIndex == 8 ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-1 large-4  large-order-3  columns graph-title">
                  <span>Recursos Financeiros disponíveis p/ Inovação (<?= $innovativenessScores[8] ?>%)</span>
                </div>
              </div>
            </div>

            <div class="small-6 large-6 medium-6 columns text-right">
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-1 large-5 large-order-1 columns graph-title">
                  <span>Liderança Comprometida com a Inovação (<?= $innovativenessScores[1] ?>%)</span>
                </div>
                <div class="small-12 medium-12 small-order-2 large-4 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[1] ?>" <?= $highestInnovativenessScoreIndex == 1 ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-2 large-3 large-order-3 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span><?= $innovativenessScores[1] ?>%</span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-1 large-5 large-order-1 columns graph-title">
                  <span>Marketing para Inovação (<?= $innovativenessScores[3] ?>%)</span>
                </div>
                <div class="small-12 medium-12 small-order-2 large-4 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[3] ?>" <?= $highestInnovativenessScoreIndex == 3 ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-2  large-3 large-order-3 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span><?= $innovativenessScores[3] ?>%</span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-1 large-5 large-order-1 columns graph-title">
                  <span>Pessoas orientadas à Inovação (<?= $innovativenessScores[5] ?>%)</span>
                </div>
                <div class="small-12 medium-12 medium-order-1 small-order-2 large-4 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[5] ?>" <?= $highestInnovativenessScoreIndex == 5 ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-2 large-3 large-order-3 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span><?= $innovativenessScores[5] ?>%</span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-1  large-5 large-order-1 columns graph-title">
                  <span>Processos Habilitadores da Inovação (<?= $innovativenessScores[7] ?>%)</span>
                </div>
                <div class="small-12 medium-12 small-order-2 large-4 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[7] ?>" <?= $highestInnovativenessScoreIndex == 7 ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-2  large-3 large-order-3 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span><?= $innovativenessScores[7] ?>%</span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
              </div>
              <div class="row graph-container">
                <div class="small-12 medium-12 small-order-1  large-5 large-order-1 columns graph-title">
                  <span>Relação com o ambiente externo (<?= $innovativenessScores[9] ?>%)</span>
                </div>
                <div class="small-12 medium-12 small-order-2 large-4 large-order-2 columns text-center">
                  <div class="graph-outer">
                    <div class="graph-inner">
                      <div class="graph" data-progress="<?= $innovativenessScores[9] ?>" <?= $highestInnovativenessScoreIndex == 9 ? 'data-highest="true"' : '' ?>>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="small-12 medium-12 small-order-2 large-3 large-order-3 columns graph-percentage show-for-large">
                  <span class="graph-percentage-label">
                    <span><?= $innovativenessScores[9] ?>%</span>
                    <hr class="graph-percentage-line"/>
                  </span>
                </div>
              </div>
            </div>

          </div>
        </div>
        <div class="small-3 medium-4 large-4 columns sidebar show-for-medium">
          <div class="row">
            <div class="columns text-center">
              <h1 class="sidebar-title">C</h1>
            </div>
            <div class="small-7 large-7 columns">
              <h3 class="sidebar-subtitle text-right">Análise da capacidade de inovação</h3>
            </div>
          </div>
          <div class="row">
            <div class="small-12 large-12 columns">
              <p class="sidebar-description text-justify">
                Veja a classificação da organização em relação a cada um dos fundamentos
                essenciais à inovação.
              </p>
              <p class="sidebar-description text-justify">
                Maior escore: <strong>
                <?php
                  switch ($highestInnovativenessScoreIndex) {
                  case 0: echo 'APRENDIZAGEM ORGANIZACIONAL'; break;
                  case 1: echo 'LIDERANÇA COMPROMETIDA COM A INOVAÇÃO '; break;
                  case 2: echo 'CULTURA DE INOVAÇÃO'; break;
                  case 3: echo 'MARKETING PARA INOVAÇÃO'; break;
                  case 4: echo 'ESTRATÉGIA ORIENTADA À INOVAÇÃO'; break;
                  case 5: echo 'PESSOAS ORIENTADAS À INOVAÇÃO'; break;
                  case 6: echo 'ESTRUTURA FAVORÁVEL À INOVAÇÃO'; break;
                  case 7: echo 'PROCESSOS HABILITADORES DA INOVAÇÃO'; break;
                  case 8: echo 'RECURSOS FINANCEIROS DISPONÍVEIS P/ INOVAÇÃO'; break;
                  case 9: echo 'RELAÇÃO COM O AMBIENTE EXTERNO'; break;
                  };
                ?>
                </strong>
              </p>
            </div>
          </div>
        </div>


      </section>

      <section class="row expanded" id="solutions">
        <div class="small-12 large-5 medium-10 medium-offset-1 large-offset-0 columns text-justify" id="solutions-title">
          <h1>Conheça</h1>
          <h2>As soluções em gestão da</h2>
          <h3><strong>Inovação <em>IEL</em></strong></h3>
          <p style="text-transform:none">
            O IEL entrega soluções que aumentarão a capacidade de sua empresa em
            inovar. Somos a <strong>única</strong> consultoria a atender em todo o
            país com uma oferta completa em inovação.
          </p>
        </div>
      </section>

      <section class="row" id="solutions-graph" >
        <div class="columns small-12">
          <img src="/img/iel/relatorio/solucoes.png" class="hide-for-small-only"/>
        </div>
      </section>

      <section class="row collapse" id="solutions-boxes" data-equalizer>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Mapeamento da Gestão da Inovação
            </div>
            <div class="solution-box-body">
              Diagnóstico para identificação e tratamento de barreiras à inovação e
              embasamento das soluções aplicáveis.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Sensibilização Interna
            </div>
            <div class="solution-box-body">
              Ponto de partida pré-intervenção para garantia de apoio de pessoal
              interno chave e outros stakeholders.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Política e Estratégia de Inovação
            </div>
            <div class="solution-box-body">
              Definição conjunta dos grandes direcionamentos de inovação da
              organização, como objetivos de inovação, parcerias, definição das
              métricas, entre outros.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Gestão de Ideias
            </div>
            <div class="solution-box-body">
              Soluções de ideação ─ levantamento e seleção de ideias de inovação,
              além da implementação de processos de coleta contínua de ideias
              inovadoras.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Projetos de Inovação
            </div>
            <div class="solution-box-body">
              Soluções de ideação ─ levantamento e seleção de ideias de inovação,
              além da implementação de processos de coleta contínua de ideias
              inovadoras.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Medição de Resultados
            </div>
            <div class="solution-box-body">
              Implementação de dashboard de monitoramento da inovação e reporte
              para gestores internos, acionistas e mercado.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Reconhecimento e premiação
            </div>
            <div class="solution-box-body">
              Componente essencial da inovação, esta solução promove o processo de
              inovação por meio de uma política personalizada e clara de
              reconhecimento interno de ideias e projetos.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Capacitações em inovação
            </div>
            <div class="solution-box-body">
              Múltiplas ofertas de capacitações, workshopes e treinamentos em
              inovação, para antes durante e depois dos projetos.
            </div>
          </div>
        </div>
        <div class="small-12 large-4 medium-4 columns">
          <div class="solution-box" data-equalizer-watch>
            <div class="solution-box-title text-center">
              Plano de Gestão da Inovação
            </div>
            <div class="solution-box-body">
              Entrega que acompanha a implementação de qualquer solução que
              permite a visualização da situação atual e estratégias de atuação em
              inovação.
            </div>
          </div>
        </div>
      </section>

      <section class="row" id="book-a-visit">
        <div class="small-12 large-12 columns">
          <h1>
            <span>Agende uma visita e veja como você pode inovar mais, na</span>
            <em>prática!</em>
          </h1>
          <h2>Cristiane Iata</h2>
          <h3>cristiane@ielsc.org.br</h3>
          <h3>(43) 3321-1254</h3>
        </div>
      </section>

      <section class="row expanded align-middle text-left" id="footer">
        <div class="small-12 large-3 medium-3 medium-offset-1 large-offset-1 ">
          <img src="/img/iel/relatorio/footer-inov-logo.png"/>
        </div>
        <div class="small-12 large-5 medium-5 text-center">
          <h6>www.iel.org.br/gestaodainovacao</h6>
        </div>
        <div class="small-12 large-2 medium-2 text-center">
          <img src="/img/iel/relatorio/footer-iel-logo.png"/>
        </div>
      </section>
    </div>

    <!-- Scripts -->
    <script type="text/javascript" src="/js/vendor/jquery.js"></script>
    <script type="text/javascript" src="/js/vendor/what-input.js"></script>
    <script type="text/javascript" src="/js/vendor/foundation.min.js"></script>
    <script src="/js/progressbar.js"></script>
    <script src="/js/relatorio.js"></script>
  </body>
</html>
