<html>
  <head>
    <title>Inovação IEL</title>
  </head>
  <body>
    <ul>
      <li><a href="#">Extrair Respostas</a></li>
      <li><a href="/admin/contacts">Editar contatos</a></li>
      <li><a href="/admin/logout">Logout</a></li>
    </ul>
    <h1>Inovação IEL: Extrair respostas</h1>
    <hr/>
    <form method="POST" action="#">
      <input type="submit" value="Extrair" />
    </form>
  </body>
</html>
