<div style="background: #006086; padding: 10px 0; color: white;">
  <div style="width: 80%; margin: 0 auto; text-align: center">
    <img src="cid:logo-email" width="80px" ?>
  </div>
  <div style="width: 80%; margin: 0 auto; text-align: center">
    <h1>Conheça seu nível de maturidade em gestão da inovação!</h1>
  </div>
</div>

<div style="width: 80%; margin: 0 auto; padding: 10px 0 30px;">
  <h3>Olá, <?= htmlspecialchars($name) ?>!</h3>
  <p style="margin-bottom: 30px;"><?= htmlspecialchars($referer) ?> achou que você poderia se interessar em saber qual é a capacidade de gestão da inovação da sua empresa.</p>

  <a href="<?= $shareUrl ?>" style="text-decoration: none; color: white; background: #EE9770; padding: 10px 20px;">QUERO CONHECER</a>
</div>

<div style="background: #006086; padding: 10px 0; color: white;">
  <div style="width: 80%; margin: 0 auto;">
    <div style="width: 100%; display: inline-block; vertical-align: middle;">
      <img src="cid:logo-iel"?>
    </div>
  </div>
</div>
