<div style="background: #006086; padding: 10px 0; color: white;">
  <div style="width: 80%; margin: 0 auto;">
    <div style="width: 15%; display: inline-block; vertical-align: middle;">
      <img src="cid:logo-email" width="80px" ?>
    </div>

    <div style="width: 80%; display: inline-block; vertical-align: middle;">
      <h1>Chegou um novo relatório de capacidade de gestão da inovação!</h1>
    </div>
  </div>
</div>

<div style="width: 80%; margin: 0 auto; padding: 10px 0 30px;">
  <h3>Olá, <?= htmlspecialchars($name) ?>!</h3>
  <p style="margin-bottom: 30px;">Recebemos um novo relatório de capacidade de gestão da inovação para <strong><?= htmlspecialchars(strtoupper($state)) ?></strong>! Seguem os dados do respondente:</p>

  <div style="background: #e3eef2; padding: 15px 25px">
    <p style="line-height: 0.7em"><strong>Nome:</strong> <span><?= htmlspecialchars($userName) ?></span></p>
    <p style="line-height: 0.7em"><strong>Email:</strong> <span><?= htmlspecialchars($userEmail) ?></span></p>
    <p style="line-height: 0.7em"><strong>Empresa:</strong> <span><?= htmlspecialchars($userCompany) ?></span></p>
    <p style="line-height: 0.7em"><strong>Cidade/UF:</strong> <span><?= htmlspecialchars($userCity) ?> / <?= htmlspecialchars(strtoupper($state)) ?></span></p>
    <p style="line-height: 0.7em"><strong>Telefone:</strong> <span><?= htmlspecialchars($userPhone) ?></span></p>
  </div>

  <p style="margin-bottom: 30px;">Veja o relatório completo clicando no botão abaixo, analise-o e entre em contato com a empresa para oferecer uma nova oportunidade de consultoria em gestão da inovação.</p>
  <a href="<?= $formUrl ?>" style="text-decoration: none; color: white; background: #EE9770; padding: 10px 20px;">Quero ver a avaliação completa</a>
</div>

<div style="background: #006086; padding: 10px 0; color: white;">
  <div style="width: 80%; margin: 0 auto;">
    <div style="width: 20%; display: inline-block; vertical-align: middle;">
      <img src="cid:logo-iel">
    </div>

    <div style="width: 75%; display: inline-block; vertical-align: middle; text-align: right;">
      <p style="display: inline-block; margin: 0 0 10px;">Link direto para o relatório:</p>
      <br/>
      <p style="background: #116A8E; padding: 5px 10px; display: inline-block; margin: 0 0 10px;"><a href="<?= $formUrl ?>" style="text-decoration: none; color: white;"><?= $formUrl ?></a></p>
    </div>
  </div>
</div>
