<div style="background: #006086; padding: 10px 0; color: white;">
  <div style="width: 80%; margin: 0 auto; text-align: center">
    <img src="cid:logo-email" width="80px" ?>
  </div>
  <div style="width: 80%; margin: 0 auto; text-align: center">
    <h1>Conheça seu nível de maturidade em gestão da inovação!</h1>
  </div>
</div>

<div style="width: 80%; margin: 0 auto; padding: 10px 0 30px;">
  <h3>Olá, <?= htmlspecialchars($name) ?>!</h3>
  <p style="margin-bottom: 30px;">Já analisamos suas respostas e temos seu diagnóstico em gestão da inovação.</p>

  <a href="<?= $formUrl ?>" style="text-decoration: none; color: white; background: #EE9770; padding: 10px 20px;">Quero ver a avaliação completa</a>
</div>

<div style="background: #006086; padding: 10px 0; color: white;">
  <div style="width: 80%; margin: 0 auto; text-align: center">
    <img src="cid:logo-iel"?>
  </div>

  <div style="width: 80%; margin: 0 auto; text-align: center">
    <p style="display: inline-block; margin: 0 0 10px;">Compartilhe seu resultado com seus amigos:</p>
    <br/>
    <p style="background: #116A8E; padding: 5px 10px; display: inline-block; margin: 0 0 10px;"><a href="<?= $formUrl ?>" style="text-decoration: none; color: white;"><?= $formUrl ?></a></p>
  </div>
</div>
